### ISSUE TITLE
failed to get `zk_evm` as a dependency of package

### ISSUE THREAD

**Issue by KittyFu307** [matter-labs/foundry-zksync#100]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dedc31e 2023-04-23T00:10:11.089859000Z)

### What command(s) is the bug in?

zsh: command not found: zkforge

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I was running `cargo build -p foundry-cli`
error: failed to get `zk_evm` as a dependency of package `zksync_types v1.0.0 (https://github.com/matter-labs/zksync-era.git#44b265bd)`
    ... which satisfies git dependency `zksync_types` (locked to 1.0.0) of package `foundry-cli v0.2.0 

Caused by:
  failed to load source for dependency `zk_evm`

Caused by:
  Unable to update https://github.com/matter-labs/era-zk_evm.git?branch=main#ca203a25

Caused by:
  object not found - no match for id (ca203a25cbff50ad623630e393dd041aca58038d); class=Odb (9); code=NotFound (-3)

**Comment by mm-zk** [comment]
Thanks. Fixed by #101
