### ISSUE TITLE
zkforge test crash "No such file or directory"

### ISSUE THREAD

**Issue by CRossel87a** [matter-labs/foundry-zksync#105]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ca28f2d 2023-06-25T17:40:20.848446304Z)

### What command(s) is the bug in?

zkforge test -vvvv --match-test testGreet

### Operating System

None

### Describe the bug

Hi,

First off, thanks for making an effort to make Forge compatible with zkSync. I am still waiting for this tool to be functional before I can start developing for this chain.

The basic sample test Greeter is failing test, both on local fork and remote:

zkforge test -vvvv --match-test testGreet

The application panicked (crashed).
Message:  Unable to read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location: cli/src/cmd/forge/test/mod.rs:501

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Installation steps was followed as instructed

**Comment by kalilinuxoo7** [comment]
Getting the same error when using fork command

**Comment by gtsui** [comment]
Following up on this - still getting this issue here as well. Anyone got a solution?

**Comment by Carolina-Pinheiro** [comment]
Any updates on this issue? I'm getting the same error.

**Comment by rrecuero** [comment]
Same here

**Comment by abarbatei** [comment]
Same for me, but slightly different line `cli/src/cmd/forge/test/mod.rs:533`

**Comment by abarbatei** [comment]
For anybody looking for a fix, the reason it fails from the start is that the devs somehow forgotten a "manual" harcoded test in the code of forge itself, namely this:
https://github.com/matter-labs/foundry-zksync/blob/3ad755ce7e639208a1f5d55f356c6471f1cfaa2c/cli/src/cmd/forge/test/mod.rs#L527-L550

Comment out these lines in the  `cli/src/cmd/forge/test/mod.rs` file and then rebuild the binary, it should work. From my slight understanding of what is going on I think this code has no impact on other parts.

**Comment by dutterbutter** [comment]
This has been updated. Please try again and post issue if any issues follow!
