### ISSUE TITLE
zkforge zkc: confusing error message when deploying a contract #80

### ISSUE THREAD

**Issue by pengbin9472** [matter-labs/foundry-zksync#106]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

zkforge zkcreate

### Operating System

Linux

### I try to deploy the smart contract before this error I have zkforge run zk-build
![1688193698440](https://github.com/matter-labs/foundry-zksync/assets/33012332/81c4cb42-60cf-428a-a078-ae438d9cef51)

**Comment by mm-zk** [comment]
Is file present? are there any other files in that directory?
