### ISSUE TITLE
forge script doesn't work

### ISSUE THREAD

**Issue by thangnn91** [matter-labs/foundry-zksync#112]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

../foundry-zksync/target/debug/zkforge script script/Counter.s.sol:CounterScript --broadcast --rpc-url zk-rpc

### Operating System

Linux

### Describe the bug

I tried to deploy my contracts using script, so some errors occurred
I used sample project at [https://github.com/sammyshakes/sample-fzksync-project](url)
And modified script with code bellow:
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

import "forge-std/Script.sol";
import {Child} from "../src/Child.sol";

contract CounterScript is Script {
    function setUp() public {}

    function run() public {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);
        // Make a new token
        Child child = new Child(1, 2);
        vm.stopBroadcast();
    }
}
```
When I ran command:
```
../foundry-zksync/target/debug/zkforge script script/Counter.s.sol:CounterScript --broadcast --rpc-url zk-rpc
```
I got the error:
`Error:
Compiler run failed
CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
   --> lib/era-system-contracts/contracts/BootloaderUtilities.sol:104:34:
    |
104 |             uint256 listLength = encodedNonce.length +
    |                                  ^^^^^^^^^^^^`
I added --via-ir, Compiler run successful but another error occurred:
`Error:
Failed to get EIP-1559 fees`

Hope to hear your support soon!

**Comment by dutterbutter** [comment]
zkforge scripting has landed. Please try again and post if any issues follow!
