### ISSUE TITLE
zksolc crash

### ISSUE THREAD

**Issue by Guanjiatai** [matter-labs/foundry-zksync#113]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

lastest

### What command(s) is the bug in?

zkforge zkbuild

### Operating System

macOS (Apple Silicon)

### Describe the bug

the application crashed when execute zkforge zkbuild.
<img width="676" alt="截屏2023-08-03 08 42 11" src="https://github.com/matter-labs/foundry-zksync/assets/139861260/1f168417-c3d5-4fb8-853d-71f068d3dcb8">

output detail is following:

<img width="791" alt="截屏2023-08-03 08 48 16" src="https://github.com/matter-labs/foundry-zksync/assets/139861260/92ff51ac-afe6-4599-9168-8384c1961b6b">

**Comment by mm-zk** [comment]
do you have the source code somewhere that you were trying to compile?

and can you provide the full command line that you run?

**Comment by Guanjiatai** [comment]
> do you have the source code somewhere that you were trying to compile?
> 
> and can you provide the full command line that you run?

Yes, you can checkout https://github.com/Uniswap/permit2 .

**Comment by superbunny-7** [comment]
https://github.com/Uniswap/universal-router

We also encountered issues when deploying this.

**Comment by Guanjiatai** [comment]
@mm-zk Please let me know if you need any help.

**Comment by dutterbutter** [comment]
We've been a lot of changes since August. Please try again and post again if any issues arise.
