### ISSUE TITLE
zk-create doesn't work for link libraries.

### ISSUE THREAD

**Issue by magj2006** [matter-labs/foundry-zksync#117]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e33b3e 2023-07-26T00:25:53.387063000Z)

### What command(s) is the bug in?

zkforge zkc 

### Operating System

macOS (Apple Silicon)

### Describe the bug

Here is a example which I am using.
Math.sol is in contracts/libraries/, and its content is :
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/**
 * @dev Standard math utilities missing in the Solidity language.
 */
library Math {
    enum Rounding {
        Down, // Toward negative infinity
        Up, // Toward infinity
        Zero // Toward zero
    }

    /**
     * @dev Returns the largest of two numbers.
     */
    function max(uint256 a, uint256 b) public pure returns (uint256) {
        return a > b ? a : b;
    }

    /**
     * @dev Returns the smallest of two numbers.
     */
    function min(uint256 a, uint256 b) public pure returns (uint256) {
        return a < b ? a : b;
    }

    /**
     * @dev Returns the average of two numbers. The result is rounded towards
     * zero.
     */
    function average(uint256 a, uint256 b) internal pure returns (uint256) {
        // (a + b) / 2 can overflow.
        return (a & b) + (a ^ b) / 2;
    }
}

Counter.sol is in contracts/ and its content is: 
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "./libraries/Math.sol";
// import "node_modules/@fikaswap/math/contracts/libraries/Math.sol";

contract Counter {
    using Math for uint256;

    uint256 public maxNumber;

    function setMaxNumber(uint256 a, uint256 b) external {
        maxNumber = a.max(b);
    }
}

I tried to use command zkforge zkb, and zkforge zkc , both are failed.

<img width="1170" alt="截屏2023-08-25 14 34 26" src="https://github.com/matter-labs/foundry-zksync/assets/8394789/0f431b82-33ad-446a-b2d2-c7e5936b71d8">

Actually, forge already support this feature, it passed when I tested on arbitrum testnet.

<img width="1180" alt="截屏2023-08-25 14 37 50" src="https://github.com/matter-labs/foundry-zksync/assets/8394789/cc535cd6-4459-4cc4-884a-0c4cf04cae80">

<img width="928" alt="截屏2023-08-25 14 39 27" src="https://github.com/matter-labs/foundry-zksync/assets/8394789/3a79a4d8-b264-41ee-a15b-679f21c996c1">

**Comment by dutterbutter** [comment]
@magj2006 You will need to deploy libraries first and then reference them in `foundry.toml` this is a requirement from the zksolc compiler.
