### ISSUE TITLE
Failed to compile smart contracts with zksolc: Compilation failed with "[]\n".

### ISSUE THREAD

**Issue by magj2006** [matter-labs/foundry-zksync#119]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e33b3e 2023-07-26T00:25:53.387063000Z)

### What command(s) is the bug in?

zkforge zkb

### Operating System

macOS (Apple Silicon)

### Describe the bug

There will be generated an error when using zkforge zkb if you define all errors in one separate file named xErrors.sol.  the output detail is:

Failed to compile smart contracts with zksolc: Compilation failed with "[]\n". Using compiler: "/abc/.zksync/zksolc-macosx-arm64-v1.3.11", with args "/abc/xErrors.sol" ["--standard-json", "--solc", "/abc/.svm/0.8.17/solc-0.8.17"]

**Comment by dutterbutter** [comment]
Can you try again to see if this issue is still a problem? @magj2006 

We've made improvements since then. Thanks!
