### ISSUE TITLE
`zkcast run` failed while inspecting: Transaction(GasMaxFeeGreaterThanPriorityFee)

### ISSUE THREAD

**Issue by AaronNan24** [matter-labs/foundry-zksync#122]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2a5ab4c 2023-09-15T02:28:45.574479000Z)

### What command(s) is the bug in?

zkcast run

### Operating System

None

### Describe the bug

<img width="1294" alt="image" src="https://github.com/matter-labs/foundry-zksync/assets/89766289/4f031551-7c0f-4cef-bc71-d92e57e2e3c9">

```
../foundry-zksync/target/debug/zkcast run --rpc-url=https://testnet.era.zksync.dev -v 0x57e5d44e487922d2167ea67e7dc4d0bbf86ca90d7f1dfbdc03ccb801bac22674
Executing previous transactions from the block.
Error:
Failed to execute transaction: 0xbbf0ced523ca006d655177765fc6cea309d5985c42dbe40d43894a7ec12235ca

Context:
- backend: failed while inspecting: Transaction(GasMaxFeeGreaterThanPriorityFee)
```
- forge 0.2.0 (2a5ab4c 2023-09-15T02:28:45.574479000Z)
- cast 0.2.0 (2a5ab4c 2023-09-15T02:28:45.574479000Z)

**Comment by Karrq** [comment]
I tried running this again but I got `tx not found: 0x57e5d44e487922d2167ea67e7dc4d0bbf86ca90d7f1dfbdc03ccb801bac22674`.
I tried looking for the tx hashes you mentioned in the issue but in both cases no tx has been found.

Do you have more information or another test case for us to verify? Thank you

**Comment by Karrq** [comment]
Hey @AaronNan24 if you have more information please feel free to reopen the issue, but for now I'll be closing it as stale. Thanks!
