### ISSUE TITLE
zkforge script throw errors

### ISSUE THREAD

**Issue by wenmoonsir** [matter-labs/foundry-zksync#142]
### Component

zkForge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e7ff88 2023-04-04T00:11:28.439758000Z)

### What command(s) is the bug in?

zkforge script script/Counter.s.sol

### Operating System

macOS (Intel)

### Describe the bug

Hi, I'm trying to run zkforge script just like how i ran forge script. But it throws

$ zkforge script script/Counter.s.sol
[⠒] Compiling...
No files changed, compilation skipped
*** Starting ERA transaction: block: 0 timestamp: 0 - but using 0 and 0 instead with nonce 0
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)
Location: /Users/stevennguyen/.cargo/git/checkouts/era-revm-d43a402504d3e115/dc04c89/src/factory_deps.rs:33

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
zsh: abort      zkforge script script/Counter.s.sol

---
Tried my best to find solutions around but couldn't. really appreciate if i could get some help. Thanks!!

**Comment by dutterbutter** [comment]
`zkforge script` is not yet supported by `zksolc`. We are actively working on this, so will update the issue here once its been completed. Thanks for posting!

**Comment by dutterbutter** [comment]
We have added support for zkforge scripting! Please try again and post if any issues follow!
