### ISSUE TITLE
EvmError: Revert while setUp()

### ISSUE THREAD

**Issue by 4NNNN** [matter-labs/foundry-zksync#207]
### Component

zkForge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

zkforge test

### Operating System

macOS (Intel)

### Describe the bug

[FAIL. Reason: EvmError: Revert] setUp() (gas: 0)

**Comment by dutterbutter** [comment]
This should be resolved but please re-open if otherwise.
