### ISSUE TITLE
[FEAT] Update `zksolc_manager` to auto fetch latest compiler

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/foundry-zksync#208]
## Description 

The current implementation of `zksolc_manager` references hardcoded `zksolc` versioning which requires constantly updating to retrieve latest versions. 

### Solution

Similar to hardhat-zksolc plugin we should be checking for latest `zksolc` and fetching if there is an updated version. In addition re-evaluating the usage of `.zksync` for default compiler download location.

**Comment by elfedy** [comment]
It's debatable if we want to do this at this point as sometimes new compiler versions contain breaking changes so me might want to "officially" support it before having it download automatically on existing projects
