### ISSUE TITLE
Error when run cmd `cargo build --release`

### ISSUE THREAD

**Issue by wVindice** [matter-labs/foundry-zksync#233]
Error: could not compile `anvil` (bin "anvil")`

**Comment by dutterbutter** [comment]
hey @wVindice 

What OS are you using to run? Can you try to do a `cargo clean` prior to running build? 

I cannot reproduce locally and our CI seems to be building fine.

**Comment by wVindice** [comment]
Thanks @dutterbutter 
im using Ubuntu 23.04, and here is my configuration:
OS: Ubuntu 23.04 x86_64
Kernel: 6.2.0-39-generic
Shell: bash 5.2.15
DE: GNOME 44.3
WM: Mutter
Terminal: gnome-terminal
CPU: Intel i5-8265U (8) @ 3.900GHz
GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620]
Memory: 2017MiB / 7783MiB
rustc 1.75.0 (82e1608df 2023-12-21)
cargo 1.75.0 (1d8b05cdd 2023-11-20)

I have tried deleting the foundry-zksync folder on my local machine, cloned from the `main` branch, then ran the `cargo clean` command and continued with the instructions. Everything was fine until I ran the `cargo build --release` command, and I encountered the following error:
`error: could not compile zkevm_test_harness (lib)`
