### ISSUE TITLE
Compiler Fails to Respect Configuration for Non-Inlinable Libraries Deployment

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/foundry-zksync#260]
## Description:
When attempting to compile non-inlinable libraries (such as `Maths.sol` used in `Counter.sol`, see mentioned repo below), the compiler does not respect the library addresses specified in the `foundry.toml` configuration file. This issue occurs even after manually deploying the libraries and updating the configuration. The expected behaviour is for the compiler to recognize and use the deployed library addresses during the compilation process, similar to the HH solc plugin's handling of such cases.

### Steps to Reproduce:
1. Clone the example repository: `git clone https://github.com/kelemeno/example-zkfoundry`
2. Attempt to build the project: `zkforge zkbuild`
3. Notice the compilation error related to the `Maths.sol` library.

### Expected Behavior:
Users should be able to compile and deploy libraries like `Maths.sol` separately, update the `foundry.toml` configuration with the deployed library address, and have the compiler recognize this configuration. In the current implementation what _should_ work but does not:

- Compilation of specific contracts via `zkforge zkbuild --contracts-to-compile "Maths.sol"`
- `zkforge zkcreate src/Maths.sol:Maths --private-key <PRIVATE-KEY> --rpc-url https://127.0.0.1:8011/ --chain 260`
- Update configuration `foundy.toml` with specified library / address
- `zkforge test --rpc-url http://127.0.0.1:8011/ --chain 260`
- Errors

### Suggested Improvements:
- Follow same procedure as HH solc plugin 
- Implement a `detect-missing-libraries` flag similar to the HH solc plugin.
- Upon detecting missing libraries, prompt the user to deploy them and automatically update the `foundry.toml` configuration to streamline the process using a similar command as below. Example command after libraries are detected in HH plugin:
```
yarn hardhat deploy-zksync:libraries  --compile-all-contracts --private-key <PRIVATE_KEY> --network zkSyncLocal
```

**Note:** If you have a process idea that improves the DevXP please mention it below. This is simply what the HH solc plugin does, and how it handles the same requirement. 

### Relevant Links:
- [Compile non-inlinable libraries  in zkSync](https://docs.zksync.io/build/tooling/hazrdhat/compiling-libraries.html#manual-deployment)
- [HH solc plugin for zkSync](https://github.com/matter-labs/hardhat-zksync/tree/main/packages/hardhat-zksync-solc)
- [HH solc repo](https://github.com/matter-labs/hardhat-zksync/tree/main/packages/hardhat-zksync-solc)

**Comment by aon** [comment]
Hey @dutterbutter. I'm working on this issue and I think DevXP could be improved. The workflow I'm thinking of is:

1. Developer attempts to build the project with `zkforge zkbuild`.
2. Compilation fails due to missing library dependencies.
3. Developer is prompted to deploy libraries first. Information of missing library dependencies is saved to a temporary file in the project.
4. User runs `zkforge zkcreate --deploy-missing-libraries --private-key <PRIVATE_KEY> --rpc-url <RPC_URL> --chain <CHAIN>`
5. Libraries are built and deployed following the necessary order to avoid having missing library dependencies, e.g.:
    a. Contract `Counter` depends on library `Math` which itself depends on library `FixedPoint`.
    b. Zkforge detects this dependency tree, and starts by building and deploying `FixedPoint`.
    c. After `FixedPoint` has been deployed, `Math` library is built and deployed linking the address of the deployed `FixedPoint` library.
    d. Finally, `Counter` contract is built and deployed linking with all the deployed libraries.

Let me know if you think this could improve the current DevXP.

**Comment by dutterbutter** [comment]
Hey @Jrigada 

Yes, the proposed approach works. What are your thoughts immediately compiling once the missing libraries are deployed, avoiding the last prompt to run `zkforge zkbuild`.

**Comment by aon** [comment]
Yes, that's a great idea. I'll add that to the last step.
