### ISSUE TITLE
console2.logString not working

### ISSUE THREAD

**Issue by marcellobardus** [matter-labs/foundry-zksync#270]
### Component

zkForge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8e59dd1 2024-02-19T18:41:44.292656000Z)

### What command(s) is the bug in?

zkforge test -vvvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

`console2.logString` seems to make no effect, no info is being logged to stdout.
 The issue can be reproduced by  `zkforge init hello_zkfoundry`, change the autogenerated test to:
```
 function test_Increment() public {
        console2.logString("setNumber");
        counter.increment();
        assertEq(counter.number(), 1);
    }
```

Then run `zkforge test -vvvvv`.
No `setNumber` is visible in `stdout`.

**Comment by zhangninghai** [comment]
I have this problem too.，zkforge test --match-path xxx.t.sol --rpc-url    Unable to use

**Comment by dutterbutter** [comment]
Fixed in `dev` branch with new approach.
