### ISSUE TITLE
zkforge zkbuild Error:  Failed to compile smart contracts with zksolc

### ISSUE THREAD

**Issue by yohanelly95** [matter-labs/foundry-zksync#285]
### Component

zkForge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4307bfb 2024-03-20T06:25:29.717831000Z)

### What command(s) is the bug in?

 zkforge zkbuild and zkforge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I run `zkforge zkbuild` I get the error:
```
Error: 
Failed to compile smart contracts with zksolc: Could not assign standard_json to writer
```
How do I resolve this? Is there a flag or anything required here.

**Comment by yohanelly95** [comment]
I have tried install zksolc v1.4.0 and using it from a folder like 
```
zkforge zkbuild --use zk/zksolc 
Error: 
Failed to compile smart contracts with zksolc: Could not assign standard_json to writer
```
but I still get the same error, 
```
Error: 
Failed to compile smart contracts with zksolc: Could not assign standard_json to writer
```

**Comment by yohanelly95** [comment]
Issue seems to occur with all zkforge related commands. How do I fix this compiler issue? @bxpana

**Comment by OmegaTymbJIep** [comment]
@yohanelly95 What I see you tried to specify **zksol** compiler with `--use` option. But this option is for **sol** compiler, see `zkforge zkbuild --help`. Try to use `--use-zksolc` instead. And, also, if I am not mistaken you can't currently specify the path to the `zksol` compiler (despite `--help` saying it), only the version is supported.

**Comment by yohanelly95** [comment]
> @yohanelly95 What I see you tried to specify **zksol** compiler with `--use` option. But this option is for **sol** compiler, see `zkforge zkbuild --help`. Try to use `--use-zksolc` instead. And, also, if I am not mistaken you can't currently specify the path to the **zksol** compiler (despite `--help` saying it), only the version is supported.

I see, what is the fix/workaround required then? This error persists 
```
Error: 
Failed to compile smart contracts with zksolc: Could not assign standard_json to writer
```

**Comment by zhangninghai** [comment]
When will it be solved?

**Comment by OmegaTymbJIep** [comment]
Try to remove the `zkout` in the project with contracts, that appear after `zkforge zkbuild` and contain artifacts. Remove zksolc compiler, which should be at `~/.zksync/zksolc-<OS>-<ARCH>-<ZKSOLC_VERSION>`. And try to rebuild with specifying options `--use` and `--use-zksolc`. In my case I've used `zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0`.

**Comment by dutterbutter** [comment]
Hey @yohanelly95 

Can you provide a repo that I may reproduce the issue?

**Comment by yohanelly95** [comment]
> Hey @yohanelly95
> 
> Can you provide a repo that I may reproduce the issue?

Sure, can try it in this repository. https://github.com/razor-network/bridge-proxy/

**Comment by yohanelly95** [comment]
> Hey @yohanelly95
> 
> Can you provide a repo that I may reproduce the issue?

I am just running the zkbuild command inside a `zkforge init new_project` directory. So it only has the Counter.sol and related deployer.

**Comment by yohanelly95** [comment]
> Hey @yohanelly95
> 
> Can you provide a repo that I may reproduce the issue?

I have pushed the changes to bridge_v2 folder here https://github.com/yohanelly95/foundry-zksync @dutterbutter

**Comment by yohanelly95** [comment]
> @yohanelly95 Try to remove the `zkout` in the project with contracts, that appear after `zkforge zkbuild` and contain artifacts. Remove zksolc compiler, which should be at `~/.zksync/zksolc-<OS>-<ARCH>-<ZKSOLC_VERSION>`. And try to rebuild with specifying options `--use` and `--use-zksolc`. In my case I've used `zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0`.

when I run `zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0` I get the error ```
Message:  called `Result::unwrap()` on an `Err` value: Error("missing field `contracts`", line: 1, column: 3944)
Location: crates/common/src/zk_compile.rs:1165

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    54284 abort      zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0
```
I have shared the repo details in the message above @OmegaTymbJIep

**Comment by milaabl** [comment]
> > @yohanelly95 Try to remove the `zkout` in the project with contracts, that appear after `zkforge zkbuild` and contain artifacts. Remove zksolc compiler, which should be at `~/.zksync/zksolc-<OS>-<ARCH>-<ZKSOLC_VERSION>`. And try to rebuild with specifying options `--use` and `--use-zksolc`. In my case I've used `zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0`.
> 
> when I run `zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0` I get the error
> 
> ```
> Message:  called `Result::unwrap()` on an `Err` value: Error("missing field `contracts`", line: 1, column: 3944)
> Location: crates/common/src/zk_compile.rs:1165
> 
> This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
> 
> Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
> Run with RUST_BACKTRACE=full to include source snippets.
> [1]    54284 abort      zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0
> ```
> 
> I have shared the repo details in the message above @OmegaTymbJIep

I have the exact same error running `zkforge test` *(I assume it throws during a compilation phase!)*.

Just running `zkforge test` in a newly scaffolded project (ran `zkforge init sampletest` to generate a new project).

**Comment by milaabl** [comment]
The stack trace points to this line:

![image](https://github.com/matter-labs/foundry-zksync/assets/86361434/debaf2d2-b55e-44aa-8f76-fe933903bb0f)

**Comment by milaabl** [comment]
@OmegaTymbJlep, your suggestion does not work either:

```bash
zkforge zkbuild --use-zksolc v1.3.23
zksolc not found in `.zksync` directory. Downloading zksolc compiler from https://github.com/matter-labs/zksolc-bin/releases/download/v1.3.23/zksolc-linux-amd64-musl-v1.3.23
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Error("missing field `contracts`", line: 1, column: 2081)
Location: crates/common/src/zk_compile.rs:1164

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted
```

**Comment by yohanelly95** [comment]
> > > @yohanelly95 Try to remove the `zkout` in the project with contracts, that appear after `zkforge zkbuild` and contain artifacts. Remove zksolc compiler, which should be at `~/.zksync/zksolc-<OS>-<ARCH>-<ZKSOLC_VERSION>`. And try to rebuild with specifying options `--use` and `--use-zksolc`. In my case I've used `zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0`.
> > 
> > 
> > when I run `zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0` I get the error
> > ```
> > Message:  called `Result::unwrap()` on an `Err` value: Error("missing field `contracts`", line: 1, column: 3944)
> > Location: crates/common/src/zk_compile.rs:1165
> > 
> > This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
> > 
> > Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
> > Run with RUST_BACKTRACE=full to include source snippets.
> > [1]    54284 abort      zkforge zkbuild --use 0.8.13 --use-zksolc v1.4.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have shared the repo details in the message above @OmegaTymbJIep
> 
> I have the exact same error running `zkforge test` _(I assume it throws during a compilation phase!)_.
> 
> The problem occurs during just running `zkforge test` in a newly scaffolded project (ran `zkforge init sampletest` to generate a new project).

same here, the error comes up when running zkforge commands in a scaffolded project. In my case `bridge_v2`

**Comment by milaabl** [comment]
@zhangninghai, do you have the same problem too?

**Comment by dutterbutter** [comment]
Hey folks 👋 

We are in the process of releasing a new version of our Foundry implementation that will handle these situations much better. I apologize for the inconvenience currently being experienced, as this is an early alpha version we appreciate the reported issue. We are tracking to make a pre-release of the new version this week.

**Comment by Jrigada** [comment]
Hey @yohanelly95! we've deprecated `zkforge zkbuild` in favor of `forge build --zksync `that provides a better user experience. Could you please verify with forge instead? The same applies to test and script. This version of foundry should improve the user experience. Thank you for raising the issue

**Comment by elfedy** [comment]
The original reported issue is known to happen when `zksolc` tries to use a `solc` version it doesn't support. For now, the way to troubleshoot is either try to use a newer version of `zksolc` via the `zksolc` option in foundry toml, or try to specify an older version of `solc` that the current version. Running `forge` with `RUST_LOG=trace` may help to determine which versions of each compiler are being used. The UX should be improved when solving https://github.com/matter-labs/foundry-zksync/issues/208 and https://github.com/matter-labs/foundry-zksync/issues/428.
Closing as this has been stale for a while. If the issue is still there and it's not due to what has been stated above, please reopen and we can try to troubleshoot.
