### ISSUE TITLE
`zkforge build` crashes on solidity errors

### ISSUE THREAD

**Issue by alpinevm** [matter-labs/foundry-zksync#291]
### Component

zkForge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

(normal) forge 0.2.0 (f9da73d 2024-03-24T00:18:58.485997283Z)

### What command(s) is the bug in?

zkforge build

### Operating System

Linux

### Describe the bug

When running `zkforge zkbuild --use 0.8.20 --use-zksolc v1.4.0` on a contract with a solidity syntax error the compiler crashes:
```sh
$ RUST_BACKTRACE=full zkforge zkbuild --use 0.8.20 --use-zksolc v1.4.0
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Error("missing field `contracts`", line: 1, column: 316)
Location: crates/common/src/zk_compile.rs:1165

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  <empty backtrace>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted (core dumped)
```

Output of `forge build` on the same project for reference:
```sh
$ forge build
[⠊] Compiling...
[⠒] Compiling 3 files with 0.8.20
[⠢] Solc 0.8.20 finished in 2.14ms
Error:
Compiler run failed:
Error (2314): Expected ';' but got '}'
 --> src/NFT.sol:7:2:
  |
7 | 	}
  | 	^
```
Was able to reproduce this with a few different types of solidity errors.

**System Info:**
zkforge version:
```
$ zkforge -V
forge 0.2.0 (89ef0f4 2024-03-24T23:48:59.091477116Z)
```
Compiled from source with command:
```
$ cargo install --path ./crates/zkforge --profile local --force --locked
```
Rust version info:
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/user/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2023-09-30-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-2023-09-30-x86_64-unknown-linux-gnu (default)
rustc 1.74.0-nightly (8ce4540bd 2023-09-29)

```
Machine info:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by milaabl** [comment]
I have the same issue as you, too!! I'm running Windows WSL, but @yohanelly95 is getting the same error on MacOS. (#285)

**Comment by dutterbutter** [comment]
Hey folks 👋 

We are in the process of releasing a new version of our Foundry implementation that will handle these situations much better. I apologize for the inconvenience currently being experienced, as this is an early alpha version we appreciate the reported issue. We are tracking to make a pre-release of the new version this week.

**Comment by nbaztec** [comment]
This should be fixed in the most recent `forge` version. We've deprecated `zkforge` in favor of `forge --zksync` that provides a better user experience.

**Comment by milaabl** [comment]
@dutterbutter, @nbaztec, thank you!! Will surely check it out.
