### ISSUE TITLE
Assertion error: calldataEncoding too big

### ISSUE THREAD

**Issue by brotherlymite** [matter-labs/foundry-zksync#296]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4307bfb 2024-03-20T16:57:57.936401000Z)

### What command(s) is the bug in?

zkforge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `zkforge test` is giving the following error: 

```
2024-04-02T05:36:44.010724Z ERROR foundry_evm_core::era_revm::transactions: tx execution halted: virtual machine entered unexpected state. 
Please contact developers and provide transaction details that caused this error. 
Error description: Assertion error: calldataEncoding too big
The application panicked (crashed).

Message:  HALT: virtual machine entered unexpected state. 
Please contact developers and provide transaction details that caused this error. 
Error description: Assertion error: calldataEncoding too big

Location: ./foundry-zksync/crates/evm/core/src/era_revm/transactions.rs:305
```

I'm not able to share the exact code of the test file as the repository is currently private - but will update once it has been made public.

**Comment by nbaztec** [comment]
Hi @brotherlymite, we've deprecated `zkforge test` in favor of `forge test --zksync` that provides a better user experience. Could you please verify with `forge` instead? And if possible, please share a reproducible example so we can debug this further.

**Comment by Karrq** [comment]
Is there any update here? I'll be closing this as stale for now, there have been plenty of changes since this issue has been raised, and without a reproducible example we aren't able to verify if the issue has been resolved already.
Feel free to reopen if there's new information. Thank you.
