### ISSUE TITLE
vm.writeJson cheatcode gives: `Failed to parse json` error

### ISSUE THREAD

**Issue by brotherlymite** [matter-labs/foundry-zksync#297]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4307bfb 2024-03-20T16:57:57.936401000Z)

### What command(s) is the bug in?

zkforge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Getting the following error when trying to use the `vm.writeJson` cheatcode:

`ERROR era_cheatcodes::cheatcodes: Failed to parse json`

The code to reproduce the error:
```
function testWriteJson() public {
    string memory contractReport = 'contractReport';

    string memory output = vm.serializeAddress(contractReport, 'contractA', address(2));

    vm.writeJson(output, './reports/Report.json');
}
 ```

**Comment by dutterbutter** [comment]
Thanks for posting! I was able to reproduce and will work to resolve. Thanks!

**Comment by dutterbutter** [comment]
Fixed in `dev` branch with new approach.
