### ISSUE TITLE
Implement `vm.label`

### ISSUE THREAD

**Issue by brotherlymite** [matter-labs/foundry-zksync#298]
### Component

zkforge

### Describe the feature you would like

🌟 Feature Request

📝 Description

Implementing the `vm.label()` [cheat code](https://github.com/foundry-rs/book/blob/master/src/cheatcodes/label.md).

Declaration
```solidity
function label(address addr, string calldata label) external;
```

```solidity
function getLabel(address) external returns (string memory);
```

🤔 Rationale
This method is required to set a label for addr in test traces.

🖼️ Mockups / Examples

```solidity
vm.label(address(10), 'alice');
assertEq(vm.getLabel(address(10)), 'alice');
```

🎯 Task Checklist
- [ ] Implement `vm.label()` and `vm.getLabel()`
- [ ] Write tests for `vm.label()` and `vm.getLabel()`
- [ ] Add inline documentation for `vm.label()` and `vm.getLabel()`

**Comment by dutterbutter** [comment]
Thanks for the suggestion! We will be sure to include this in an early next release.

**Comment by dutterbutter** [comment]
Fixed in `dev` branch with new approach.
