### ISSUE TITLE
`assembly-to-bytecode conversion error` when trying to compile

### ISSUE THREAD

**Issue by brotherlymite** [matter-labs/foundry-zksync#300]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4307bfb 2024-03-20T16:57:57.936401000Z)

### What command(s) is the bug in?

zkforge zkb

### Operating System

macOS (Apple Silicon)

### Describe the bug

When trying to compile [ProtocolV3TestBase](https://github.com/bgd-labs/aave-helpers/blob/master/src/ProtocolV3TestBase.sol) contract using `zkforge zkbuild`, I'm getting the following error: 
```
Failed to compile smart contracts with zksolc: Compilation failed with stdout: "" and stderr: "Contract `src/ProtocolV3TestBase.sol:ProtocolV3LegacyTestBase` 

compiling error: The contract `src/ProtocolV3TestBase.sol:ProtocolV3LegacyTestBase` assembly-to-bytecode conversion error: assembly parse error 

Label fun_e2eTest was tried to be used for either PC or constant at offset 91848 that is more than `65535` addressable space

The contract `src/ProtocolV3TestBase.sol:ProtocolV3LegacyTestBase` assembly-to-bytecode conversion error: assembly parse error 

Label fun_e2eTest was tried to be used for either PC or constant at offset 91848 that is more than `65535` addressable space\n\n". 

Using compiler: "/path-to-compiler/.zksync/zksolc-macosx-arm64-v1.4.0", with args "/path-to-repo/aave-helpers/src/ProtocolV3TestBase.sol" CommandArgs { inner: ["--standard-json", "--solc", "/path/.svm/0.8.18/solc-0.8.18"] }
```

Please note running `zkforge zkbuild` directly on the [aave-helpers](https://github.com/bgd-labs/aave-helpers/tree/master) repository results in the following error as described in issue #285 and #291:

```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Error("missing field `contracts`", line: 1, column: 750)
Location: crates/common/src/zk_compile.rs:1164
```

So to reproduce the error we should delete all contracts in the repo except [ProtocolV3TestBase](https://github.com/bgd-labs/aave-helpers/blob/master/src/ProtocolV3TestBase.sol) and its dependencies and compile.

**Comment by dutterbutter** [comment]
@brotherlymite thanks for posting this issue. We will investigate but at first glance looks like the max bytecode limit of the zkevm has been met meaning there may be a need to break up the file for compilation. However, we will investigate further.

**Comment by Karrq** [comment]
https://github.com/bgd-labs/aave-helpers/pull/301
