### ISSUE TITLE
`zkforge zkbuild` does not recompile when solc version changed in `foundry.toml`

### ISSUE THREAD

**Issue by brotherlymite** [matter-labs/foundry-zksync#302]
### Component

zkforge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4307bfb 2024-03-20T16:57:57.936401000Z)

### What command(s) is the bug in?

zkforge zkbuild

### Operating System

macOS (Apple Silicon)

### Describe the bug

After being compiled once, whenever the solidity compiler version changes is being changed in `foundry.toml` for example from `solc=0.8.18` to `solc=0.8.19` the contracts are not being compiled again, which can be seen in the artifacts generated as well.

**Comment by dutterbutter** [comment]
Thanks for raising the issue! We are actively working on a V2 version that will resolve this issue. Will update this thread when available.

**Comment by Jrigada** [comment]
Hey @brotherlymite thank you for reporting this issue. Like you said in the previous version whenever the solc version was pinned in the toml it would not trigger the recompilation of the contracts. It should work now in V2, if you can try it out it would be great. I tried it myself and going from `solc="0.8.20"` to something like `solc="0.8.19"` triggers the recompilation of the contracts. 
This is shown in the terminal 
```
forge build --zksync
[⠘] Compiling 27 files with 0.8.19
[⠃] Solc 0.8.19 finished in 697.00ms
```
and can also be seen in the artifacts in `./out `changing its content. 
Thank you again for raising the issue and let me know if there is something that I missed.
