### ISSUE TITLE
Failed to compile smart contracts with zksolc: Cannot get source files: Could not get solc: Unknown version provided

### ISSUE THREAD

**Issue by zhangninghai** [matter-labs/foundry-zksync#303]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

Failed to compile smart contracts with zksolc: Cannot get source files: Could not get solc: Unknown version provided

**Comment by elfedy** [comment]
@zhangninghai are you still getting this issue. Could you provide an example to reproduce it?

**Comment by Karrq** [comment]
This issue has grown stale, and without any other information provided we'll be closing it. Feel free to reopen the issue if you have new information for us.
