### ISSUE TITLE
Broken links for binary download

### ISSUE THREAD

**Issue by dymayday** [matter-labs/foundry-zksync#313]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

In the release section, quick links to binary download are broken, only the asset section works for downloading.
https://github.com/matter-labs/foundry-zksync/releases/tag/v0.0.1-alpha.2

**Comment by dutterbutter** [comment]
@dymayday thanks this is expected behaviour as a result of how github handles pre-releases. Will update to remove for pre-releases in future releases.

**Comment by dutterbutter** [comment]
Removed in latest pre-release, as seen here: https://github.com/matter-labs/foundry-zksync/releases/tag/v0.0.2-alpha.3
