### ISSUE TITLE
Bloated asset archives

### ISSUE THREAD

**Issue by dymayday** [matter-labs/foundry-zksync#314]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

In the release page for [v0.0.1-alpha.2](https://github.com/matter-labs/foundry-zksync/releases/tag/v0.0.1-alpha.2) the archives contain too much stuff :
` 
 build
 deps
 examples
 incremental
 zkcast
 zkcast.d
 zkforge
 zkforge.d
`

I guess this should only contain the executables and not the entire `target/release` folder.
This will reduce drastically the size of the archives and enable us to use them in our CI pipelines.

Thanks

**Comment by dutterbutter** [comment]
Thanks for the suggestion will investigate and update accordingly.

**Comment by dutterbutter** [comment]
Updated the release workflow to only include binaries from `release/`: https://github.com/matter-labs/foundry-zksync/pull/312. Will see this change in the next `alpha.4` release.
