### ISSUE TITLE
Failed to install v0.0.2-alpha.3

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/foundry-zksync#325]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4603195 2024-04-10T00:21:30.172477000Z)

### What command(s) is the bug in?

installation

### Operating System

macOS (Intel)

### Describe the bug

Attempting to install on the latest release on MacOS:

```bash
git clone https://github.com/matter-labs/foundry-zksync
cd foundry-zksync
git checkout v0.0.2-alpha.3
cargo build --release
```

Followed by an insanely long output:
```bash
error: failed to run custom build command for `librocksdb-sys v0.11.0+8.1.1`

Caused by:
  process didn't exit successfully: `/Users/patrick/code/foundry-zksync/target/release/build/librocksdb-sys-68ab0e7cac38859e/build-script-build` (exit status: 1)
...
```

**Comment by PatrickAlphaC** [comment]
I tried to switch to `dev` and install from there, and am running into this:

```
error: failed to run custom build command for `openssl-sys v0.9.101`
```

**Comment by PatrickAlphaC** [comment]
```
 stack backtrace:
     0: _rust_begin_unwind
     1: core::panicking::panic_fmt
     2: openssl_src::Build::run_command
     3: openssl_src::Build::build
     4: build_script_main::find_vendored::get_openssl
     5: build_script_main::find_openssl
     6: build_script_main::main
     7: core::ops::function::FnOnce::call_once
```

**Comment by dutterbutter** [comment]
@PatrickAlphaC 👋  

In the README we have a prerequisite for MacOs users. Can you please do the following:

#### MacOS Prerequisite - Install make: MacOS users need to ensure make is installed. If not, install it using Homebrew:
```
brew install make
```

Then, set the path to GNU make:

`export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"`

Add this export line to your shell profile (~/.bash_profile, ~/.zshrc, etc.) to make the change permanent.

This should resolve the OpenSSL issue experienced here.

**Comment by PatrickAlphaC** [comment]
I have `make` installed and the path exported. I am still running into the same issue.

**Comment by dutterbutter** [comment]
is homebrew installed in the path `/opt/homebrew/`

**Comment by PatrickAlphaC** [comment]
```
$ which brew
/usr/local/bin/brew
```

Perhaps this is the issue?

**Comment by dutterbutter** [comment]
ahh i see I overlooked the intel macos usage. 

You will need to update the path to point to your installation path so:

```
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
```

**Comment by PatrickAlphaC** [comment]
Yep, that fixed it!

```
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
```

Thanks!

**Comment by dutterbutter** [comment]
Relevant PR: #326
