### ISSUE TITLE
hosted docker image

### ISSUE THREAD

**Issue by silvercondor** [matter-labs/foundry-zksync#340]
### Component

Foundryup

### Describe the feature you would like

hi, is it possible to host a docker image so i can run zk-cast commands similar to 

https://book.getfoundry.sh/tutorials/foundry-docker

i have tried building the docker image locally but it fails

**Comment by ETeissonniere** [comment]
@dutterbutter if you have interest in a PR from my side to enable this, I am happy to spend some time on it as we are pretty into using docker wherever we can for Nodle.

Out of the blue I'd say all that is needed is a github action to build the [provided Dockerfile](https://github.com/matter-labs/foundry-zksync/blob/dev/Dockerfile) and push it to GHCR. This should be relatively straightforward and something I can get to you quickly.

Only thing we'd need insights on would be whether you want the [container metadata](https://github.com/matter-labs/foundry-zksync/blob/30ad9f82ef88eb40132723b8c50a5dfc05fe35ba/Dockerfile#L44) to be modified.
