### ISSUE TITLE
[Dep Update] Update foundry-compilers to 0.3.13 to support 0.8.25 solc

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/foundry-zksync#341]
## Description

Now that zksolc 1.4.1 is available and supports the latest solc an update is necessary to `foundry-compilers` dependency to add support for `0.8.25`. The required changes are available in this [diff](https://github.com/foundry-rs/foundry/pull/7424/files).

**Comment by alexroan** [comment]
This is currently a blocker for 0.8.25

**Comment by Karrq** [comment]
As per @elfedy's [comment](https://github.com/matter-labs/foundry-zksync/pull/360#issuecomment-2148397689), we now support solc 0.8.25.
