### ISSUE TITLE
buffer overrun while deserializing

### ISSUE THREAD

**Issue by bonedaddy** [matter-labs/foundry-zksync#345]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

Linux

### Describe the bug

I'm attempting to use the anvil binary built from this repository to fork mainnet. While attempting to perform an `eth_call` to read a `uint256` after forking mainnet, attempting to deserialize the call response returns an error

```
Caused by:
    0: buffer overrun while deserializing
    1: buffer overrun while deserializing
```

The exact same code works when calling a mainnet zksync rpc

**Comment by dutterbutter** [comment]
Anvil should not be used with zkSync forking as its very different implementation which is why its not included in the binary releases. 

For forking mainnet separately we advise making use of [era-test-node ](https://github.com/matter-labs/era-test-node).
