### ISSUE TITLE
Verification fails

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/foundry-zksync#362]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Intel)

### Describe the bug

```
forge verify-contract 0xD3F8D13E3e1d0c978A242eA71b177E5D04586F4B Counter --verifier-url "https://zksync2-mainnet-explorer.zksync.io/contract_verification" --chain-id 324
```

This is a basic `Counter` contract created after running `forge init`. I was able to deploy it, but unable to verify it. Here is the output with foundry running in debug mode. 

```
2024-05-03T16:36:15.377139Z ERROR etherscan: Failed to deserialize response: EOF while parsing a value at line 1 column 0 res=""
Error: 
Failed to deserialize content: EOF while parsing a value at line 1 column 0
```

**Comment by dutterbutter** [comment]
@PatrickAlphaC verification is currently unsupported but will be added soon. As described under the limitations section of the README here: https://github.com/matter-labs/foundry-zksync?tab=readme-ov-file#limitations

**Comment by PatrickAlphaC** [comment]
Ah whoops. Sorry, thanks!

**Comment by PatrickAlphaC** [comment]
Does it make sense to reopen this though? I'm assuming this would be on the roadmap.

**Comment by jarrodwatts** [comment]
Can we consider reopening this to track progress / discuss plans for implementation?
