### ISSUE TITLE
Create2 revert, if done via SystemContractsCaller.systemCallWithReturndata

### ISSUE THREAD

**Issue by vladenysiuk** [matter-labs/foundry-zksync#364]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (eda9078 2024-05-03T00:24:49.741164000Z)

### What command(s) is the bug in?

forge test --is-system true --zksync

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I try to execute low level system call to deployer system contract to execute create2 --- execution reverts:

```
contract TestDeploy is Test {
    
    
    function test_Deploy() public {
        address deployerWallet = makeAddr("deployer");
        vm.prank(deployerWallet);
        Auxiliary aux = new Auxiliary();
        aux.deploy(beaconProxyBytecodeHash, salt);
        
    }
}
```

deploy function (should be executed in zkEVM as external call):

```
contract Auxiliary{
    function deploy(bytes32 l2TokenProxyBytecodeHash,bytes32 salt) public {
        (bool success, bytes memory returndata) = SystemContractsCaller.systemCallWithReturndata(
            uint32(gasleft()),
            DEPLOYER_SYSTEM_CONTRACT,
            0,
            abi.encodeCall(
                IContractDeployer.create2,
                (salt, l2TokenProxyBytecodeHash, abi.encode(address(0), ""))
            )
        );
        if(!success) {
            assembly {
                returndatacopy(0,0,returndatasize())
                revert(0, returndatasize())
            }
        }
    }
```
    
    
    Forge output:
    Failing tests:
        Encountered 1 failing test in test/foundry/TestDeploy.t.sol:TestDeploy
        [FAIL. Reason: EvmError: Revert] test_Deploy() (gas: 37420)
        
   foundry.toml:
  
[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'

[profile.zksync]
src = 'contracts'
libs = ['lib']
fallback_oz = true
test = 'test/foundry'
is_system = true
mode = "3"

**Comment by elfedy** [comment]
@vladenysiuk I managed to create a working example that performs a `create2` call via `SystemContractsCaller.systemCallWithReturndata` successfully. This test passes for me:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {SystemContractsCaller} from "era-contracts/system-contracts/contracts-preprocessed/libraries/SystemContractsCaller.sol";
import {IContractDeployer} from "era-contracts/system-contracts/contracts-preprocessed/interfaces/IContractDeployer.sol";
import {Test, console} from "forge-std/Test.sol";
import {Counter} from "src/Counter.sol";

address constant DEPLOYER_SYSTEM_CONTRACT = 0x0000000000000000000000000000000000008006;

contract TestDeploy is Test {
    function test_Deploy() public {
        string memory artifact = vm.readFile("zkout/Counter.sol/Counter.json");
        bytes32 bytecodeHash = vm.parseJsonBytes32(artifact, ".hash");
        bytes32 salt = "1234";

        Auxiliary aux = new Auxiliary();
        address add = aux.deploy(bytecodeHash, salt);

        Counter counter = Counter(add);
        counter.setNumber(42);
        counter.increment();
        assert(counter.number() == 43);
    }
}

contract Auxiliary {
    function deploy(
        bytes32 bytecodeHash,
        bytes32 salt
    ) public returns (address) {
        bytes memory bytecode = type(Counter).creationCode;

        IContractDeployer deployer = IContractDeployer(
            DEPLOYER_SYSTEM_CONTRACT
        );

        address expected = deployer.getNewAddressCreate2(
            address(this),
            bytecodeHash,
            salt,
            abi.encode(address(0), "")
        );

        (bool success, bytes memory returndata) = SystemContractsCaller
            .systemCallWithReturndata(
                uint32(gasleft()),
                DEPLOYER_SYSTEM_CONTRACT,
                0,
                abi.encodeCall(
                    IContractDeployer.create2,
                    (salt, bytecodeHash, abi.encode(address(0), ""))
                )
            );

        if (!success) {
            assembly {
                returndatacopy(0, 0, returndatasize())
                revert(0, returndatasize())
            }
        }
        address ret = abi.decode(returndata, (address));
        assert(ret == expected);
        return ret;
    }
}
```
Could you try if it works for you on our latest release? If it doesn't there is some context missing for the example you provided:

1. To set zksync specific options in `foundry.toml` you should use `[profile.default.zksync]` rather than `[profile.zksync]`
2. `is_system` should be `enable_eravm_extensions` if passed on `foundry.toml` or `--zk-enable-eravm-extensions` if passed through the cli
3. How do you get `beaconProxyBytecodeHash`? computing the hash outside at the raw test level will yield the evm bytecode. In the example I am reading it from the json artifact. Also how do you specify the salt?
4. Bytecode for the given bytecode hash needs to be known by the compiler when the create2 two call is being made. See [this](https://docs.zksync.io/build/developer-reference/ethereum-differences/evm-instructions#create-create2)

**Comment by dutterbutter** [comment]
This has been resolved. For min reproduction you can view this example: https://github.com/dutterbutter/min-zksync-create2
