### ISSUE TITLE
Missing libraries is blank

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/foundry-zksync#369]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (a7196c2 2024-05-09T00:24:42.563510000Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Intel)

### Describe the bug

I have a library that my contracts use as a dependency. 

```
library HuffDeployer {
```

When I compile this, I get:
```
Error: 
Failed to compile with zksolc: Missing libraries detected [ZkMissingLibrary { contract_name: "HuffDeployer", contract_path: "lib/foundry-huff/src/HuffDeployer.sol", missing_libraries: [] }]

Run the following command in order to deploy the missing libraries:
forge create --deploy-missing-libraries --private-key <PRIVATE_KEY> --rpc-url <RPC_URL> --chain <CHAIN_ID> --zksync
```

But in my `missing_library_dependencies.json` I have this:

```json
[
  {
    "contract_name": "HuffDeployer",
    "contract_path": "lib/foundry-huff/src/HuffDeployer.sol",
    "missing_libraries": []
  }
]
```

Why is the `missing_libraries` empty? Even for testing locally do I have to deploy the library?

**Comment by dutterbutter** [comment]
Re-opening as this seems to disrupt the experience a lot. Will investigate a solution.

**Comment by wshino** [comment]
私は現在以下のrepositoryをzksyncに対応させようとしています。
https://github.com/zkemail/ether-email-auth

zkSync sepoliaにnon-inliable librariesをデプロイしたのでbuildは成功します。
しかし、libraryを参照するtest caseは、libraryを参照する時点でEvm revertが発生し、テストが失敗します。
例えば以下の行で失敗します。
https://github.com/zkemail/ether-email-auth/blob/feat/foundry-zksync/packages/contracts/src/EmailAuth.sol#L204

**Comment by wshino** [comment]
I am currently trying to apply the foundry-zksync in the following repositories:
https://github.com/zkemail/ether-email-auth

I deployed non-inliable libraries to zkSync sepolia, so forge build has been succeeded.
However, a test case that references library will cause an Evm revert at the point of referencing library, and the test will fail.
For example, the following line fails
https://github.com/zkemail/ether-email-auth/blob/feat/foundry-zksync/packages/contracts/src/EmailAuth.sol#L204

Can't we test locally when referring to a library?

**Comment by Karrq** [comment]
The empty `missing_libraries` here is because those would be `HuffDeployer`'s libraries. 

In this case, `HuffDeployer` itself _is_ the missing library, and it has no further libraries. Altough the source is present, this is a non-inlineable library, thus it needs to be deployed on chain for the compilation to succeed.

Note that you might stumble upon #382 in that case, and for now I recommend switching to a script instead of a test (as described in my reply to that issue).

If you have further questions on running the script let's move the conversation to the other issue, and if you feel that you received a proper answer to your issue, you can go ahead and close it. Thanks!

**Comment by nbaztec** [comment]
@PatrickAlphaC Also the missing libraries file we expect is `.zksolc-libraries-cache/missing_library_dependencies.json`. There's currently no way to reconfigure it. Could you verify that as well please?

**Comment by PatrickAlphaC** [comment]
> Could you verify that as well please?

Verify what? That I cannot reconfigure this file? 

Seems like the TL;DR is that we cannot run scripts inside of tests as such. I'd like to keep this open, as this is very annoying and means I have to make a different development environment for zkSync. I don't think that's the developer experience we are looking for.

**Comment by Karrq** [comment]
The discussion has veered away from the original issue, which, as described [earlier](https://github.com/matter-labs/foundry-zksync/issues/369#issuecomment-2136163390), seems to have been a non-issue.

**Comment by hedgar2017** [comment]
@dutterbutter @Karrq we're currently migrating to new LLVM-based assembler and linker, where it will be possible to implement post-compile-time linking the devs are looking for.
