### ISSUE TITLE
`skip` and `avoid-contracts` seem to not be working. 

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/foundry-zksync#372]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (01f61ff 2024-05-11T00:24:53.177450000Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Intel)

### Describe the bug

```
forge init
```

Update `Counter.t.sol` to not be compileable. Maybe with something like this:

```javascript
    function setUp() public {
        hello
    }
```

then, run this:

```
RUST_LOG=debug forge build --skip Counter.t.sol --zksync
```

It will incorrectly try to compile the contract we are skipping. Without the `--zksync` flag, it works fine.

**Comment by dutterbutter** [comment]
@PatrickAlphaC I will look to reproduce, it seems to be working for me at first glance.

**Comment by dutterbutter** [comment]
@PatrickAlphaC you will need to use the following command:

```
RUST_LOG=debug forge build --skip Counter.t.sol --avoid-contracts Counter.t.sol --zksync
```

We intend to consolidate skip and avoid-contracts in a future release.
