### ISSUE TITLE
Compile fails with `Stack too deep` error

### ISSUE THREAD

**Issue by aon** [matter-labs/foundry-zksync#380]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (13497a5 2024-05-15T00:25:37.094964000Z)

### What command(s) is the bug in?

forge build --zksync

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge build --zksync` fails compiling https://github.com/matter-labs/era-contracts/tree/main/system-contracts with `Stack too deep` error:

![image](https://github.com/matter-labs/foundry-zksync/assets/21188659/a9f4544f-0293-4fd1-b782-3ca40fbb946b)

Following suggestion from compiler using `--via-ir` flag, compile still fails with a different error:

![image](https://github.com/matter-labs/foundry-zksync/assets/21188659/85015017-414f-48d1-a407-ba054e541c25)

**Comment by dutterbutter** [comment]
@aon this needs to be compiled with the `-is-system` flag set to `true`. Not sure if you are doing so.

**Comment by Karrq** [comment]
There are several factors at play here, but in particular here it seems you'd need to use matter-labs's custom version of solc (available [here](https://github.com/matter-labs/era-solidity)).

You will need to configure `forge` to use it via `zk_solc_path` (since #406)

**Comment by Karrq** [comment]
We now have better Yul support with #421. Please use the latest `zksolc` compiler (1.5.0) and make sure you are using the zksync's solc fork (any appropriate version ending with -1.0.1)
