### ISSUE TITLE
chore(repo): update foundry-compilers to 0.3.13 to support 0.8.25 solc

### ISSUE THREAD

**Issue by plonukob** [matter-labs/foundry-zksync#383]
The same update to 0.3.13 is needed here as in https://github.com/matter-labs/foundry-zksync/issues/341
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.lock#L4546
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.toml#L141

**Comment by dutterbutter** [comment]
Duplicate of #341

**Comment by plonukob** [comment]
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.lock#L4546

This is exactly what is not a duplicate. https://github.com/matter-labs/foundry-zksync/issues/341 only fixed:
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.toml#L141


@dutterbutter
