### ISSUE TITLE
chore: update foundry-compilers to 0.3.13

### ISSUE THREAD

**Issue by plonukob** [matter-labs/foundry-zksync#385]
I don't see any solutions to upgrade this particular file to version 0.3.13 in this repository.
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.lock#L4546

This is exactly what is not a duplicate. https://github.com/matter-labs/foundry-zksync/issues/341 only fixed:
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.toml#L141

@dutterbutter

**Comment by Karrq** [comment]
As per @elfedy's [comment](https://github.com/matter-labs/foundry-zksync/pull/360#issuecomment-2148397689), we moved to a custom fork (with the intent of merging with upstream eventually), so this isn't relevant anymore.
