### ISSUE TITLE
unknown selector `0xdb4235f6` for VmCalls (no support for keyExistsJson)

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/foundry-zksync#388]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (dc4b81f 2024-05-21T15:26:16.686968000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

1. Install foundry-zksync
2. `forge init`
3. Set your `Counter.s.sol` to the following:

```javascript
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";

contract CounterScript is Script {
    function setUp() public {}

    function run() public {
        bool exists = vm.keyExistsJson('{"hi": "true"}', ".hi");
        console.log(exists);
    }
}
```

4. Run the script:
```
forge script script/Counter.s.sol 
```

You'll get an output like:

```
✓ Compiled 20 files!     
Traces:
  [121871] → new CounterScript@0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
    └─ ← 498 bytes of code

  [98] CounterScript::setUp()
    └─ ← ()

  [2994] CounterScript::run()
    ├─ [0] VM::keyExistsJson("{\"hi\": \"true\"}", ".hi") [staticcall]
    │   └─ ← unknown selector `0xdb4235f6` for VmCalls
    └─ ← unknown selector `0xdb4235f6` for VmCalls


Gas used: 24058
Error: 
script failed: unknown selector `0xdb4235f6` for VmCalls
```

However, run it with vanilla foundry:
```
foundryup
 forge script script/Counter.s.sol
```

and you'll get:

```
Script ran successfully.
Gas used: 27031

== Logs ==
  true
```

**Comment by RonTuretzky** [comment]
also experiencing this on forge 2cb8757

**Comment by Karrq** [comment]
As @nbaztec already mentioned [here](https://github.com/matter-labs/foundry-zksync/pull/392#issuecomment-2127222524), this is due to the cheatcode in question (and possibly others) being added [after](https://github.com/foundry-rs/foundry/pull/7317) our latest update from upstream foundry.
Currently we are in the process of updating our fork to upstream, which will add support to this cheatcode as well as others that have been added since then.

**Comment by Karrq** [comment]
Tracking in #443
