### ISSUE TITLE
`forge create` does not work

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/foundry-zksync#391]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (13497a5 2024-05-22T00:24:24.116664000Z)

### What command(s) is the bug in?

forge create

### Operating System

macOS (Intel)

### Describe the bug

Forge create does not deploy contracts. 

1. Create a new repo
```
forge init
```

2. Try to deploy 

```
forge create Counter --rpc-url ${ZKSYNC_SEPOLIA_RPC_URL} --private-key $PRIVATE_KEY
```

You'll get:
```
Error: 
(code: -32600, message: Unsupported method: eth_feeHistory on zksync, data: None)
```

So if you add the `--legacy` flag, you'll get:

```
Error: 
(code: 3, message: Failed to serialize transaction: toAddressIsNull, data: None)
```

So if you add --zksync flag, meaning the whole command is:
```
forge create Counter --rpc-url ${ZKSYNC_SEPOLIA_RPC_URL} --private-key $PRIVATE_KEY --legacy --zksync
```

You'll get
```
Error: 
(code: 3, message: ErrorObject { code: ServerError(3), message: "not enough gas to publish compressed bytecodes", data: Some(RawValue("0x")) }, data: Some(String("0x")))
```

However, doing this on zksync mainnet passes. It only fails on zksync sepolia.

**Comment by ciaranightingale** [comment]
If I run the following command:
```
forge create Counter --rpc-url $ZKSYNC_SEPOLIA_RPC_URL --private-key $PRIVATE_KEY --legacy --zksync
```
The deployment succeeds (For `Counter.sol`)
Were you using Counter here or one of the Updraft challenges?

**Comment by PatrickAlphaC** [comment]
Ok, after a second try it worked.
