### ISSUE TITLE
Discrepancy between foundry-zksync and zksync-sepolia

### ISSUE THREAD

**Issue by sendra** [matter-labs/foundry-zksync#403]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (1f3160e 2024-05-30T00:22:09.630097000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

**Problem:**

Trouble debugging why a bridging transaction fails on zksync-sepolia side.
- [sepolia tx](https://sepolia.etherscan.io//tx/0x27eeb87ea74b85983f1cdd80abfb6aea361041b28cd850c883653192fccf9d37)
- [zksync-sepolia](https://sepolia-era.zksync.network/tx/0xb78cee719d4e6e8d59f99b5b7c784d5021774448ba593db568444fe7fa71f71a)

Also a weird value is shown on the [View](https://sepolia-era.zksync.network/txsDeposits) page for L1->L2 transactions, with value: 79,598,458,911,708,134,998 (T)

**How to reproduce:**

To locally reproduce error, to try and debug, execute:
`forge test --match-contract ZkSyncAdapterTest --match-test test_receiveMessage -vvvv`
on the code on this [branch](https://github.com/bgd-labs/aave-delivery-infrastructure/tree/feat/zksync)

This will execute a [test](https://github.com/bgd-labs/aave-delivery-infrastructure/blob/3b401df263d5e1ad246dcae0b0458e5e4b3d3df6/tests/adapters/ZkSyncAdapter.t.sol#L272) that forks zksync-sepolia on the block of the failing transaction. This test calls the same method as the failing tx with the expected aliased caller. It checks that all the on chain configs are correct, previous to the call, and checks that all the expected events and state changes happen after the call (It uses the deployed addresses, without using mocks).

The problem is that the test execution on the fork works as it should, while the execution on the testnet chain doesn't.

This was done using the dev branch of foundry-zksync

**Comment by Karrq** [comment]
This issue was resolved internally by setting a manual gas limit higher than calculated by foundry - we have opened #418 to track this.

Thank you for the report!
