### ISSUE TITLE
Add scripting to list of incompatibilities

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/foundry-zksync#408]
### Component

Forge

### Describe the feature you would like

At the moment, using `vm` cheatcodes are not compatible when working with `zksync-foundry`. You can see a rationale for it in [this comment here](https://github.com/matter-labs/foundry-zksync/issues/389#issuecomment-2140713720).

Because of this, testing scripts is not possible, and we should not encourage people to use scripts that cannot be tested. 

If we don't want to say it's outright incompatible, we should at least discourage using scripting and devops with the zkSync environment. And 100% say that using cheatcodes isn't supported.

**Comment by dutterbutter** [comment]
This is now available with: https://github.com/matter-labs/foundry-zksync/pull/569
