### ISSUE TITLE
Inaccurate gas estimation

### ISSUE THREAD

**Issue by Karrq** [matter-labs/foundry-zksync#418]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (8cb46fa4 2024-06-05T13:34:46.413496000Z)

### What command(s) is the bug in?

forge script

### Operating System

None

### Describe the bug

When using `forge script` to deploy contracts, `forge` [attempts](https://github.com/matter-labs/foundry-zksync/blob/b826f67f7a6950f053af7076742386465a8fc633/crates/forge/bin/cmd/script/broadcast.rs#L455) to calculate the exact gas required to execute a given transaction on the target chain (with `--broadcast` flag).

Currently, this estimation is inaccurate due to differing gas parameters, which sometimes can lead to failures when broadcasting these transactions on chain.

**Comment by dutterbutter** [comment]
@Karrq is this still relevant, if so what is the status?

**Comment by Karrq** [comment]
We did improve gas estimation considerably recently, but haven't been able to check the results of the estimation personally, so we need to run some tests before updating the issue

/cc @elfedy

**Comment by elfedy** [comment]
As of today, the estimation (which involves txs running locally using the rpc fork parameters) is in fact innacurate, however the gas limit of the tx is [overriden](https://github.com/matter-labs/foundry-zksync/blob/15b47588df3a9a2d6934927189e387277e43e3b2/crates/script/src/broadcast.rs#L136) with the estimation from an rpc call, which currently renders the simulation useless for us. We should at least show the right gas parameters and also do some tests comparing the estimation vs rpc_call, maybe it makes sense to use the estimation directly.

**Comment by dutterbutter** [comment]
@elfedy is this closed from https://github.com/matter-labs/foundry-zksync/pull/773?
