### ISSUE TITLE
chore: error in controbutor role 

### ISSUE THREAD

**Issue by potiore** [matter-labs/foundry-zksync#420]
Hey @Karrq! I apologize for opening this issue, but it's pretty important to me.

Can I get a Contributor for this issue https://github.com/matter-labs/foundry-zksync/issues/384? It was merged, I think it's the same as PR, because it was based on it.

**Comment by nbaztec** [comment]
@potiore this is not how GitHub or the FOSS community works. There's no "giving" a contributor role for filing issues. A contributor is someone who has helped the open source community by directly adding functionality or fixing a bug in an open source project. The contribution must also be meaningful and relevant. Issues are usually reported by the community during their use of the FOSS tools and as they encounter any blockers or limitations on their projects. Filing trivial PRs simply to gain a contributor status or to farm airdrops goes against the open-source ethos and our community principles. 

Please feel free to contribute to any open source community in future with the guidelines mentioned above.
