### ISSUE TITLE
No `broadcast` file created

### ISSUE THREAD

**Issue by hensha256** [matter-labs/foundry-zksync#422]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (fd4066b1 2024-06-06T19:12:48.861429000Z)

### What command(s) is the bug in?

forge create

### Operating System

macOS (Apple Silicon)

### Describe the bug

I ran `forge create --zksync` to deploy a smart contract to zksync era, and no broadcast file was created.

I was deploying this [smart contract](https://github.com/Uniswap/view-quoter-v3/blob/update-create2-formula/contracts/Quoter.sol) - the URL includes the branch `update-create2-formula` which I was on.

**Comment by Jrigada** [comment]
Hey @hensha256!
Thank you for raising this issue. The broadcast file is created when using `forge script` with the `--broadcast` flag enabled. We don't create the file when using `forge create`. Would you mind trying the same process but using a script?

Thank you, and let me know if anything else comes up.
