### ISSUE TITLE
Error when running invariant tests with targetSelector

### ISSUE THREAD

**Issue by alexkeating** [matter-labs/foundry-zksync#424]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge 0.0.2 (3891bda 2024-06-12T00:21:02.437682807Z)

### Operating System

Linux

### Describe the bug

When I run [tests that reference targetSelector](https://github.com/uniswapfoundation/UniStaker/blob/887d7dc0c1db3f17227d13af4d8a791a66912d42/test/UniStaker.invariants.t.sol#L40) I get more or less the same error for all of my invariant tests:

```
[FAIL. Reason: failed to set up invariant testing environment: [targetSelectors] address does not hav
e an associated contract: 0x6b3D9bf4377eF0A0BE817B9e7B8D486AEE3b7876] invariant_RewardPerTokenAccumul
atedCheckpoint_should_be_greater_or_equal_to_the_last_rewardPerTokenAccumulatedCheckpoint() (runs: 0,
 calls: 0, reverts: 0)
```

**Comment by Jrigada** [comment]
Hello @alexkeating

Thank you for raising the issue. It brought to our attention that invariant testing was not working as expected for zk-compiled contracts. We merged a [PR](https://github.com/matter-labs/foundry-zksync/pull/441) yesterday that should fix the issue and make it possible to run invariant tests with the --zksync flag.

Feel free to contact us if anything else comes up.
