### ISSUE TITLE
Unable to run `forge test` without --zksync flag

### ISSUE THREAD

**Issue by hensha256** [matter-labs/foundry-zksync#442]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (fd4066b1 2024-06-06T17:01:06.704615000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to use regular foundry to run tests on the EVM (_not_ zksync).
I can run `forge build` just fine. But when I then run `forge test`, it tries to compile my code for `zksync` even though i do not have the flag enabled.

```
forge build
[⠊] Compiling...
[⠘] Compiling 125 files with 0.8.24
[⠊] Solc 0.8.24 finished in 10.20s
Compiler run successful with warnings:
...
```

and then 
```
forge test
[⠊] Compiling...
No files changed, compilation skipped
[⠔] Compiling (zksync)...^C
```

the zksync compilation then fails and i cannot run my tests for EVM chains.

**Comment by Karrq** [comment]
Fixed by #435. Please update to f505a53
