### ISSUE TITLE
Unable to specify custom zksolc compiler

### ISSUE THREAD

**Issue by brotherlymite** [matter-labs/foundry-zksync#449]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge 0.0.2 (f505a536 2024-06-26T15:14:31.411368000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

When trying to compile using custom zksolc compiler via using the flag `forge build --zksync --zk-solc-path ./path-to-zksolc-compiler` flag getting the following error `Broken pipe (os error 32)`.

Also when trying to specify the zksolc compiler in `foundry.toml` like `zksolc='./path-to-compiler'`, for example when specifying the v1.5.1 compiler executable path and running `forge build --zksync` v1.4.1 is being downloaded automatically in `~./zksync/` and is being used instead of the zksolc compiler specified.

**Comment by Karrq** [comment]
Hi! 
The `zksync.solc` configuration option (`--zk-solc-path`) is meant to specify a custom version of `solc` that `zksolc` will use, therefore please do not use it to specify a `zksolc` compiler, which should instead (as you pointed out also) be specified in `zksync.zksolc`.

We are investigating the issue in regards to v1.5.1 being ignored.

**Comment by brotherlymite** [comment]
Using `[profile.default.zksync]` in `foundry.toml` it worked fine for me. Thank you.
