### ISSUE TITLE
"./install-foundry-zksync" not working

### ISSUE THREAD

**Issue by Chathura-Ahangama** [matter-labs/foundry-zksync#472]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3ae4f505 2024-07-07T04:28:54.758287900Z)

### What command(s) is the bug in?

./install-foundry-zksync

### Operating System

Windows

### Describe the bug

When I follow the instructions for quick install ,I cloned the repo and as the last command when i run "./install-foundry-zksync" it throws an error .Here it is

   "...foundryup-zksync: installing foundry (version nightly, tag nightly)
foundryup-zksync: downloading latest forge, and cast
##################################################################################################################################################### 100.0%
Archive:  /tmp/tmp.MohwuZYRfX/foundry-zksync.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmp.MohwuZYRfX/foundry-zksync.zip or
        /tmp/tmp.MohwuZYRfX/foundry-zksync.zip.zip, and cannot find /tmp/tmp.MohwuZYRfX/foundry-zksync.zip.ZIP, period.
foundryup-zksync: command failed: unzip /tmp/tmp.MohwuZYRfX/foundry-zksync.zip -d /c/Users/chath/.foundry/bin"

**Comment by ronijaat** [comment]
Did you find any solutions?

**Comment by maikelordaz** [comment]
Is any solution for this? I've only managed to make it work in WSL

**Comment by PatrickAlphaC** [comment]
Are you all using "raw" windows? Or windows with WSL?

**Comment by ronijaat** [comment]
> Are you all using "raw" windows? Or windows with WSL?

windows with WSL

**Comment by Chathura-Ahangama** [comment]
Windows with WSL

**Comment by maikelordaz** [comment]
> Are you all using "raw" windows? Or windows with WSL?

For me works fine on WSL. But not on windows

**Comment by Chathura-Ahangama** [comment]
> > Are you all using "raw" windows? Or windows with WSL?
> 
> For me works fine on WSL. But not on windows

By the time I log this issue,this error were thrown in both "raw" windows with gitbash and wsl.so I'll try back with wsl,if it works then

**Comment by Dday52** [comment]
![2024-08-07 05_07_33-ubuntu](https://github.com/user-attachments/assets/f092c77b-c86d-4ed5-b0a9-b9bab5f09d9b)
How can i fix this

**Comment by ronijaat** [comment]
> ![2024-08-07 05_07_33-ubuntu](https://private-user-images.githubusercontent.com/105000352/355650307-f092c77b-c86d-4ed5-b0a9-b9bab5f09d9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTY4NjQsIm5iZiI6MTcyMjk5NjU2NCwicGF0aCI6Ii8xMDUwMDAzNTIvMzU1NjUwMzA3LWYwOTJjNzdiLWM4NmQtNGVkNS1iMGE5LWI5YmFiNWYwOWQ5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwMjA5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTMxMjhlZTJhNGZiYjQyYzBmYjcwNjg3NjFhMGIyMTIwNWZkZjliNmE5YWU2YzNlZGMzMWMwNGQyOWUwMGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-nfaNWVlv4rhhcFVsTWkWHAy2yF1ZCMrUWSKvPclEEk) How can i fix this

first install foundry in this project and do zksync stuff

**Comment by Dday52** [comment]
> > ![2024-08-07 05_07_33-ubuntu](https://private-user-images.githubusercontent.com/105000352/355650307-f092c77b-c86d-4ed5-b0a9-b9bab5f09d9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTY4NjQsIm5iZiI6MTcyMjk5NjU2NCwicGF0aCI6Ii8xMDUwMDAzNTIvMzU1NjUwMzA3LWYwOTJjNzdiLWM4NmQtNGVkNS1iMGE5LWI5YmFiNWYwOWQ5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwMjA5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTMxMjhlZTJhNGZiYjQyYzBmYjcwNjg3NjFhMGIyMTIwNWZkZjliNmE5YWU2YzNlZGMzMWMwNGQyOWUwMGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-nfaNWVlv4rhhcFVsTWkWHAy2yF1ZCMrUWSKvPclEEk) How can i fix this
> 
> first install foundry in this project and do zksync stuff

i did,foundry installed without problem,then when i wanna install zksync this error appear

**Comment by Dday52** [comment]
![2024-08-07 16_29_38-foundry](https://github.com/user-attachments/assets/267bca00-2c63-48e1-aa57-dc44dca55717)

**Comment by ronijaat** [comment]
> ![2024-08-07 16_29_38-foundry](https://private-user-images.githubusercontent.com/105000352/355835809-267bca00-2c63-48e1-aa57-dc44dca55717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzg0MDYsIm5iZiI6MTcyMzAzODEwNiwicGF0aCI6Ii8xMDUwMDAzNTIvMzU1ODM1ODA5LTI2N2JjYTAwLTJjNjMtNDhlMS1hYTU3LWRjNDRkY2E1NTcxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMzQxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzYxOTUyZmQ1NmY0NDAxN2U5MDU1MTY0MDExNWU5NTllMmVjY2NkNThiN2MxYmQzOGEzNDIxMjg5MTg1NmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uHpi4QswiDkIaY0_y00wY_aN384uKuoZLT7ekQViOng)

I had the same issue

Do this
1. curl -L https://foundry.paradigm.xyz | bash
2. foundryup
3. ./install-foundry-zksync

**Comment by Dday52** [comment]
> > ![2024-08-07 16_29_38-foundry](https://private-user-images.githubusercontent.com/105000352/355835809-267bca00-2c63-48e1-aa57-dc44dca55717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzg0MDYsIm5iZiI6MTcyMzAzODEwNiwicGF0aCI6Ii8xMDUwMDAzNTIvMzU1ODM1ODA5LTI2N2JjYTAwLTJjNjMtNDhlMS1hYTU3LWRjNDRkY2E1NTcxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMzQxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzYxOTUyZmQ1NmY0NDAxN2U5MDU1MTY0MDExNWU5NTllMmVjY2NkNThiN2MxYmQzOGEzNDIxMjg5MTg1NmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uHpi4QswiDkIaY0_y00wY_aN384uKuoZLT7ekQViOng)
> 
> I faced the same issue
> 
> Do this
> 
> 1. curl -L https://foundry.paradigm.xyz | bash
> 2. foundryup
> 3. ./install-foundry-zksync

i updated ubuntu wsl to 22 and this error is fixed,i was ou wsl 20

**Comment by ronijaat** [comment]
> > > ![2024-08-07 16_29_38-foundry](https://private-user-images.githubusercontent.com/105000352/355835809-267bca00-2c63-48e1-aa57-dc44dca55717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzg0MDYsIm5iZiI6MTcyMzAzODEwNiwicGF0aCI6Ii8xMDUwMDAzNTIvMzU1ODM1ODA5LTI2N2JjYTAwLTJjNjMtNDhlMS1hYTU3LWRjNDRkY2E1NTcxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMzQxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzYxOTUyZmQ1NmY0NDAxN2U5MDU1MTY0MDExNWU5NTllMmVjY2NkNThiN2MxYmQzOGEzNDIxMjg5MTg1NmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uHpi4QswiDkIaY0_y00wY_aN384uKuoZLT7ekQViOng)
> > 
> > 
> > I faced the same issue
> > Do this
> > 
> > 1. curl -L https://foundry.paradigm.xyz | bash
> > 2. foundryup
> > 3. ./install-foundry-zksync
> 
> i updated ubuntu wsl to 22 and this error is fixed,i was ou wsl 20

Great 👍🏻

**Comment by Karrq** [comment]
Hi, as written in the [official foundry documentation](https://book.getfoundry.sh/getting-started/installation#using-foundryup), neither PowerShell nor CMD are supported with `foundryup`. 
We have not added further Windows support to this fork, thus we won't expect our `foundryup-zksync` to work either.

For future reference, we specified that our support for Windows is limited (#500).

@Chathura-Ahangama could you please confirm if you were able to succesfully install using WSL? And if so, could you close the issue? Thank you.

**Comment by maikelordaz** [comment]
> Hi, as written in the [official foundry documentation](https://book.getfoundry.sh/getting-started/installation#using-foundryup), neither PowerShell nor CMD are supported with `foundryup`. 
> 
> We have not added further Windows support to this fork, thus we won't expect our `foundryup-zksync` to work either.
> 
> 
> 
> For future reference, we specified that our support for Windows is limited (#500).
> 
> 
> 
> @Chathura-Ahangama could you please confirm if you were able to succesfully install using WSL? And if so, could you close the issue? Thank you.

Yes, but on git bash foundry works perfect without the need of WSL

**Comment by Karrq** [comment]
> Yes, but on git bash foundry works perfect without the need of WSL

Were you able to install `foundry-zksync` on git bash, @maikelordaz ? Or have you encountered issues? Could you share what error are you getting with git bash? same as OP?

**Comment by maikelordaz** [comment]
> > Yes, but on git bash foundry works perfect without the need of WSL
> 
> Were you able to install `foundry-zksync` on git bash, @maikelordaz ? Or have you encountered issues? Could you share what error are you getting with git bash? same as OP?

Mine is a proble with windows, foundry works fine on git bash, but foundry-zksync I can only run it on wsl. 
this is the output 
![image](https://github.com/user-attachments/assets/0ef3bcbe-4da2-48ca-a4e0-7c35328c2f18)

**Comment by Chathura-Ahangama** [comment]
@Karrq I still cannot install foundry zksync using git bash.But it works in wsl.
![Zksync-issue](https://github.com/user-attachments/assets/0af2d85b-ec4e-4bba-8051-dc444e765f0f)

**Comment by ShadabImran07** [comment]
You said correctly working fine in wsl but having issue in git bash
