### ISSUE TITLE
Contract deploy bug in fork test

### ISSUE THREAD

**Issue by spengrah** [matter-labs/foundry-zksync#503]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (bde6d97 2024-08-05T00:25:00.218693000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm running a fork test and foundry-zksync is panic-ing with the below error when it hits [the part of my test code](https://github.com/Hats-Protocol/zksync-proposer-mvp/blob/4c0be4ea73ab62630cd28ddd99a6e93696b785bf/test/StreamManager.t.sol#L77) that deploys my contract-under-test.

I've tried deploying from my tests with both regular old create (e.g. `new StreamManager(args)`) and create2 (e.g. with `new StreamManager{salt: SALT}(args)`), and both give the same error.

I'm having trouble determining whether the "failed finding contract for {bytecode}" error is a deployment bug or a fork test bug, or maybe something else.

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/110bd0b8-1c28-42b4-bfb8-9be5b9d6b99b">

**Comment by nbaztec** [comment]
Hi @spengrah we've recently disabled building zksync artifacts by default in tests so the recommended way is to either:

* provide `--zk-compile` to compile the artifacts and switch the zkVM via cheatcode or fork, or 
* use `--zksync` that will start the test in zkVM mode and enables `zk-compile` implcitly.

**Comment by spengrah** [comment]
Thanks @nbaztec! Adding the `--zk-compile` flag to my `forge test` command worked perfectly
