### ISSUE TITLE
build --sizes does not work properly (false negative error code)

### ISSUE THREAD

**Issue by sakulstra** [matter-labs/foundry-zksync#504]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (bde6d97 2024-08-06T00:23:04.629842000Z)

### What command(s) is the bug in?

forge build --sizes

### Operating System

macOS (Apple Silicon)

### Describe the bug

foundry zksync will report exceeding size for:
```
| AaveV3ZkSync_AaveV3ZkSyncActivation_20240805        |   51,360 |    -26,784 |
```
and thus exit with exit code 1 although, we're able to deploy it on zksync mainnet just fine

As reproduction you can:
1. checkout https://github.com/bgd-labs/aave-proposals-v3/tree/feat/zksync-activation
2. run `FOUNDRY_PROFILE=zksync forge build --sizes --zksync`

**Comment by nbaztec** [comment]
Closed via #505
