### ISSUE TITLE
Docs installation guide does not work

### ISSUE THREAD

**Issue by davd-ops** [matter-labs/foundry-zksync#531]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

Doesn't matter

### What command(s) is the bug in?

git clone git@github.com:matter-labs/foundry-zksync.git

### Operating System

macOS (Apple Silicon)

### Describe the bug

The official docs say that user can install this by running:

Step 1: Clone the repository:
git clone git@github.com:matter-labs/foundry-zksync.git

Step 2: Navigate to the project directory:
cd foundry-zksync

Step 3: Run the Installer: Execute the script to install the foundry-zksync binaries forge and cast
./install-foundry-zksync

But the first step fails, instead, the user should use git clone https://github.com/matter-labs/foundry-zksync.git

Here is screenshot of how it looks with docs method vs the one I suggested:
<img width="936" alt="image" src="https://github.com/user-attachments/assets/2d7512be-b437-4cca-8a72-72b50678fc04">

**Comment by Karrq** [comment]
See [this comment](https://github.com/matter-labs/foundry-zksync/issues/498#issuecomment-2263398114) for how to configure your system to be able to clone via ssh, and see [this other comment](https://github.com/matter-labs/foundry-zksync/issues/363#issuecomment-2137125057) for the reasoning behind this type of link.

Closing as duplicate.
