### ISSUE TITLE
[foundryup-zksync] version `GLIBC_2.3X' not found

### ISSUE THREAD

**Issue by igorlnunes** [matter-labs/foundry-zksync#583]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (03ea54c 2024-09-18T16:31:08.207328652Z)

### What command(s) is the bug in?

foundryup-zksync

### Operating System

Linux

### Describe the bug

**Operating System**

- Operating System: Linux Mint 20.3
- Kernel: Linux 5.4.0-171-generic
- Architecture: x86-64

1) run the installer:
```bash
curl -L https://raw.githubusercontent.com/matter-labs/foundry-zksync/main/install-foundry-zksync | bash
```

2) using the `foundryup-zksync` command, the system returns:
```bash
foundryup-zksync 


.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

 ╔═╗ ╔═╗ ╦ ╦ ╔╗╔ ╔╦╗ ╦═╗ ╦ ╦         Portable and modular toolkit
 ╠╣  ║ ║ ║ ║ ║║║  ║║ ╠╦╝ ╚╦╝    for Ethereum Application Development
 ╚   ╚═╝ ╚═╝ ╝╚╝ ═╩╝ ╩╚═  ╩                 written in Rust.

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

Fork of    : https://github.com/foundry-rs/
Repo       : https://github.com/matter-labs/foundry-zksync/
Book       : https://book.getfoundry.sh/   

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

foundryup-zksync: installing foundry (version nightly, tag nightly)
foundryup-zksync: downloading latest forge, and cast
################################################################################################################################################################## 100,0%
foundryup-zksync: downloading manpages
################################################################################################################################################################## 100,0%
/home/igor/.foundry/bin/forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/igor/.foundry/bin/forge)
/home/igor/.foundry/bin/forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/igor/.foundry/bin/forge)
/home/igor/.foundry/bin/forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/igor/.foundry/bin/forge)
foundryup-zksync: command failed: /home/igor/.foundry/bin/forge --version
foundryup-zksync: installed - 
/home/igor/.foundry/bin/cast: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/igor/.foundry/bin/cast)
/home/igor/.foundry/bin/cast: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/igor/.foundry/bin/cast)
/home/igor/.foundry/bin/cast: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/igor/.foundry/bin/cast)
foundryup-zksync: command failed: /home/igor/.foundry/bin/cast --version
foundryup-zksync: installed - 
foundryup-zksync: done!
```

3) Then, when verifying the installation with the command: `forge --version`
```bash
forge --version
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by forge)
```

**Comment by Karrq** [comment]
Hey @igorlnunes, looking at your report and system information I'd say this is caused by our release binaries being built with an [ubuntu-22.04](https://github.com/matter-labs/foundry-zksync/blob/e2e2d57197cbdd5fac7fc3c197becb8584780d59/.github/workflows/release.yml#L80) runner, which makes the resulting binary depend on a newer version of GLIBC [2.35](https://launchpad.net/ubuntu/jammy/+package/libc6) than what is available in Linux Mint 20.3 (which is based on Ubuntu 20.04, so it would be using [2.31](https://launchpad.net/ubuntu/focal/+package/libc6)).
The relatively simple solution to your issue is compiling the project from source, which you can do (and also install) with:
`cargo install --git https://github.com/matter-labs/foundry-zksync --profile release --locked forge cast`

**Comment by FurkanSezal** [comment]
Hi @Karrq , when i try to do this `cargo install --git https://github.com/matter-labs/foundry-zksync --profile release --locked forge cast `
i am getting this errors:
There were 29 errors like this i change rust to rust nightly. Only these 3 left 
![image](https://github.com/user-attachments/assets/c55634d8-53f6-4f06-925e-bb1736e81866)

**Comment by Karrq** [comment]
Hey @FurkanSezal, the issue is unrelated, but yeah there's a specific nigthly version we make use of that's declared in the [rust-toolchain](https://github.com/matter-labs/foundry-zksync/blob/main/rust-toolchain) file.
That's the version we use for development and CI 👍
