### ISSUE TITLE
I can't git clone the repository

### ISSUE THREAD

**Issue by 0xdavinci** [matter-labs/foundry-zksync#635]
git clone https://github.com/matter-labs/foundry-zksync.git
Cloning into 'foundry-zksync'...
remote: Enumerating objects: 76915, done.
remote: Counting objects: 100% (21632/21632), done.
remote: Compressing objects: 100% (3897/3897), done.
error: RPC failed; curl 16 Error in the HTTP2 framing layeriB/s
error: 57 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by dutterbutter** [comment]
Hey @0xdavinci 

This looks like its specific to your network conditions rather then this repo.
