### ISSUE TITLE
Be explicit about latest compiler version supported

### ISSUE THREAD

**Issue by Jrigada** [matter-labs/foundry-zksync#639]
### Component

Other (please describe)

### Describe the feature you would like

We are moving to supporting only the latest zksolc compiler and we should be explicit about it to the user. Some of the changes that will be needed:

- Warn when using a version different from the “official” one supported.
- Have the supported version in docs/changelog, and clarify somewhere that we try to only support the latest version and there’s a specific version coupled to a foundry release.

**Comment by dutterbutter** [comment]
Closing in favour of https://github.com/matter-labs/foundry-zksync/issues/759
