### ISSUE TITLE
Evaluate capping the zkEVM gas limit to something different than 2^31-1

### ISSUE THREAD

**Issue by Jrigada** [matter-labs/foundry-zksync#645]
https://github.com/matter-labs/foundry-zksync/blob/cc27c50a8932f9e97c8d2e3eff1d2e1f008a72b3/crates/zksync/core/src/utils.rs#L120, 

For zkEVm transactions we set a super high gas limit but the zkEVM caps it anyways to "MAX_GAS_PER_TRANSACTION": 80000000, charging the original gas limit and then refunding at the end. Maybe just maxing it at `80_000_000` is tidier.

**Comment by elfedy** [comment]
the `80_000_000` gas cap is only for execution, the other part of the gas limit may be used to pay for pubdata, that may very well surpass that cap. Given that, it is not clear that we should cap gas limit in any way.
