### ISSUE TITLE
`era-test-node` integration

### ISSUE THREAD

**Issue by Karrq** [matter-labs/foundry-zksync#677]
Foundry only supports anvil as a local node which does not work entirely for zkSync.

- **era-test-node integration:** This would be ideal for zkSync specific local development. 

Work on integrating era-test-node in a way similar to how Anvil is currently utilized, enhancing the testing infrastructure.

Extend the zksyncNode functionality that is found in the test-helpers.

**Comment by dutterbutter** [comment]
**Some additional info here:**

We intend to rebrand era-test-node to anvil-zksync, and include in the foundryup-zksync installation script for dev convenience. Work in progress right now:
- API completeness, including `anvil` namespace 
- CLI parity with anvil for dev convenience

**Comment by dutterbutter** [comment]
Closing as we have included in installation process in #765 which is the extent of this integration atm.
