### ISSUE TITLE
Foundry is getting panicked crash at /Users/runner/work/foundry-zksync/foundry-zksync/crates/script/src/broadcast.rs:89

### ISSUE THREAD

**Issue by FaizanNehal** [matter-labs/foundry-zksync#680]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (b513e39 2024-10-16T00:24:58.499734000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to run` Uniswap v2` on my local `zksync chain`. For this purpose I am running my own chain locally, and have made necessary changes into `Uniswap v2` contract so that they can be deployed to zksync and can be compiled with `solidity ^0.8.13`.

`Uniswap v2` is successfully deployed and the token pair is also created but upon adding liquidity into the pair I am getting this error from the foundry.
![image](https://github.com/user-attachments/assets/628be7d9-59a2-4249-bda1-cc837fdd5ef8)
![image](https://github.com/user-attachments/assets/795ea730-225e-4b3b-9775-3f0ee8e26c93)

Just to make everything clear I am also adding the code in my script file:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import {UniswapV2Router02} from "../contracts/UniswapV2Router02.sol";
import {UniswapV2Pair} from "../contracts/UniswapV2Pair.sol";
import {ERC20_Token_Sample} from "../contracts/Token.sol";


contract testScript is Script {
     UniswapV2Router02 public router =UniswapV2Router02(payable(0x3e193F7E8d75c81E66d222C1182e63A8Db54802A));
     UniswapV2Pair public pair =UniswapV2Pair(0x114642199eEd33e1ad1699345E12ca2bB145b9E8);
     ERC20_Token_Sample public tokenA= ERC20_Token_Sample(0xaE7F6b4f2fF21fC5Fc52932A25faea11Bf5F509e);
     ERC20_Token_Sample public tokenB= ERC20_Token_Sample(0x922a36d29b1e991DB35b8e14C08828eC31E64Ac0);


    function run() public {
        vm.startBroadcast();
        
        console.log("ADDRESS: ",router.getPair(0xaE7F6b4f2fF21fC5Fc52932A25faea11Bf5F509e,0x922a36d29b1e991DB35b8e14C08828eC31E64Ac0));
        // now adding liquidity in the pair

        console.log(tokenA.balanceOf(0xa61464658AfeAf65CccaaFD3a512b69A83B77618));
        console.log(tokenB.balanceOf(0xa61464658AfeAf65CccaaFD3a512b69A83B77618));
        tokenA.approve(0x3e193F7E8d75c81E66d222C1182e63A8Db54802A, 100000);
        tokenB.approve(0x3e193F7E8d75c81E66d222C1182e63A8Db54802A, 100000);
        router.addLiquidity(0xaE7F6b4f2fF21fC5Fc52932A25faea11Bf5F509e, 0x922a36d29b1e991DB35b8e14C08828eC31E64Ac0, 1200, 3600, 100, 300,0xa61464658AfeAf65CccaaFD3a512b69A83B77618,0);
        
        (uint112 reserve0, uint112 reserve1, uint32 blockTimestampLast) = pair.getReserves();
        console.log("RESERVE 0: ",reserve0);
        console.log("RESERVE 1: ",reserve1);
        console.log("TIMESTAMP: ",blockTimestampLast);
        vm.stopBroadcast();
    }
}
```

As you can see I am adding the liquidity and logging it. The liquidity is getting added as you can see here:

![image](https://github.com/user-attachments/assets/400c072e-b313-48a8-826d-e5369a90e52c)

So I am assuming the foundry is panicking at line
```
vm.stopBroadcast();
```

The output error was very different and told me that it might be issue with foundry itself.

**Comment by nbaztec** [comment]
Hi @FaizanNehal could you please provide a sample repo with the other contracts (`../contracts/*`) also included

**Comment by FaizanNehal** [comment]
Hello @nbaztec I have uploaded the repo for the code here:

https://github.com/FaizanNehal/Uniswap-v2-For-ZkSync

And the contract for Wrapped ETH is here. 

https://github.com/FaizanNehal/WETH-For-ZkSync

The code in Uniswap and WETH is altered so that it can be compiled with `solidity ^0.8.0`

**Comment by Karrq** [comment]
How are you running your script? Could you give us the full command used?
Does the same issue happen when using `--slow` ?

**Comment by FaizanNehal** [comment]
Hi @Karrq For the command that is showing the error is the following. The script that is throwing the errors is `testrouter.s.sol`
```
forge script scripts/testrouter.s.sol --rpc-url http://127.0.0.1:3050 --broadcast --private-key 0xac1e735be8536c6534bb4f17f06f6afc73b2b5ba84ac2cfb12f7461b20c0bbe3 --zksync
```

I am using the rich wallets provided by matter labs at:

https://github.com/matter-labs/local-setup/blob/main/rich-wallets.json

But before that you do that, you would have to deploy Uniswap, deploy two ERC20 tokens and WETH. Make a pair of those tokens and then try to add liquidity through the router. Should I provide the commands for each of them? or is it okay

**Comment by Karrq** [comment]
Awesome, thank you.
Was trying to make sure if you were using `--slow` or not, because it might be required depending on the chain id in use, but as a general rule, if some transactions seem "out of order" it might mean that `--slow` is needed (another indicator is that simulation using state from the RPC endpoint works fine).

In your case, the broadcasted transaction seems to be failing on a `trasferFrom`, which I would expect is happening inside `router.addLiquidity`, the last of your 3 transactions (the other 2 being the `approve` calls), but from your command output it seems that this last tx is actually broadcasted first (0/3), which would be the case when txs are broadcasted with batching/out of order, but EraVM doesn't support that, hence the requirement on `--slow`.

Could you try again using `--slow` and seeing if the error persists?

**Comment by Karrq** [comment]
Hey @FaizanNehal any update here? Did using `--slow` resolve your issue? 
Thank you!

**Comment by Karrq** [comment]
The only way to run it without `--slow` would be to use a chain id that is detected as not having batching support, but that's a [rather limited list](https://github.com/matter-labs/foundry-zksync/blob/aa85b6afe6bedd041acf2d129e6640d31c0e2353/crates/cli/src/utils/cmd.rs#L219-L232), and not really a solution imo.
We may consider improving this in the future but right now there's no such work being done
