### ISSUE TITLE
foundry-zksync compilation error

### ISSUE THREAD

**Issue by Iammrgemini** [matter-labs/foundry-zksync#697]
### Component

Forge

### Describe the feature you would like

Hello team, when i use the command foundryup and then i run forge build. my code compiles without error but when i am on foundryup-zksnc and i tried to compile same code using forge build --zksync i get promted with Broken pipe ( os error 32) every attempt i make. i have been on this in the past 7 hours and i have tried to explore similar threads but all to no avail. problem still not solved. i need help in this situation please 
<img width="960" alt="Code_BRkGYlRqFo" src="https://github.com/user-attachments/assets/631a0e63-1507-4b93-9069-b5d701581d8f">

### Additional context

![Uploading Code_KBj0EYjqq7.png…]()

**Comment by dutterbutter** [comment]
@Iammrgemini can you please provide a reproducible repo for us to test?

**Comment by Iammrgemini** [comment]
i played around the solidity versions and pragma solidity 0.8.20;  was able to compile. anyone with similar problem should try to play around the solidity versions and see the one that will work thanks
