### ISSUE TITLE
cargo install: unknown feature `const_slice_index`

### ISSUE THREAD

**Issue by adraffy** [matter-labs/foundry-zksync#725]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

Linux

### Describe the bug

running `cargo install --git https://github.com/matter-labs/foundry-zksync --profile release --locked forge` since the modified installer and binaries have the `GLIBC` requirement

using latest nightly:
`cargo --version`
`cargo 1.84.0-nightly (4a2d8dc63 2024-11-09)`

encounter the following error:
```
  Compiling boojum v0.30.1
error[E0635]: unknown feature `const_slice_index`
  --> /home/raffy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boojum-0.30.1/src/lib.rs:34:12
   |
34 | #![feature(const_slice_index)]
```
https://github.com/matter-labs/era-boojum

**Comment by Karrq** [comment]
@adraffy Feel free to close the issue if that solved your problem :)

**Comment by Karrq** [comment]
Closing it as stale, please reopen if you still encounter this issue
