### ISSUE TITLE
Failing to create contract: Assertion error: factory deps non zero, data: "0x"

### ISSUE THREAD

**Issue by DicksonWu654** [matter-labs/foundry-zksync#738]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (f75d7bf 2024-11-22T00:26:55.917059070Z)

### What command(s) is the bug in?

forge create Counter --zksync --rpc-url https://sepolia.era.zksync.dev --private-key <PRIVATE_KEY>

### Operating System

Linux

### Describe the bug

Hi. I'm getting the following error:
`Error: server returned an error response: error code 3: virtual machine entered unexpected state. please contact developers and provide transaction details that caused this error. Error description: Assertion error: factory deps non zero, data: "0x"`

Steps to reproduce:
1. Install Foundry, Foundry-ZkSync
2. `forge init`
3. run: `forge create Counter --zksync --rpc-url https://sepolia.era.zksync.dev --private-key <PRIVATE_KEY>`

**Comment by DicksonWu654** [comment]
It seems like the latest version (when installing using this command: `curl -L https://raw.githubusercontent.com/matter-labs/foundry-zksync/main/install-foundry-zksync | bash`) Is the source of the problem

When using an older version (I choose a random arbitrary version: https://github.com/matter-labs/foundry-zksync/releases/tag/nightly-0b24fcc33b6eeaa837c1186366d473df9b527308) it works

**Comment by dutterbutter** [comment]
@DicksonWu654 Thanks for reporting! We are investigating the issue. In the meantime users can install previous versions as described here:

https://github.com/matter-labs/foundry-zksync/tree/main/foundryup-zksync

**Comment by uF4No** [comment]
Recommend `foundryup-zksync --version nightly-420660c5243e06af1f12febb1765a9abc9c77461` to install just the previous nightly build 🤙

**Comment by dutterbutter** [comment]
@DicksonWu654 resolved in https://github.com/matter-labs/foundry-zksync/pull/740
