### ISSUE TITLE
Deposits & withdrawals

### ISSUE THREAD

**Issue by mm-zk** [matter-labs/foundry-zksync#74]
### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

- deposit example doesn't work (is it pointing at the right URL? - shouldn't it point at L1?)
- withdrawal example: nitpick, but the amount of ETH is not in ETH but in wei?

**Comment by sammyshakes** [comment]
deposit example fixed, and yes amount is in wei
