### ISSUE TITLE
`Error: contract was not deployed` encountered when deploying simple contract to ZERO Network

### ISSUE THREAD

**Issue by jkylling** [matter-labs/foundry-zksync#766]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (15b4758 2024-12-03T00:28:11.691066908Z)

### What command(s) is the bug in?

forge create

### Operating System

Linux

### Describe the bug

I'm attempting to deploy a contract to ZERO Network using Forge by following [the instructions here](https://docs.zero.network/build-on-zero/deploy-smart-contract-to-zero#foundry), but get `Error: contract was not deployed`. Deploying the same contract to zkSync works. The wallet used for the deployment has sufficient ETH balance on both chains.

Steps to reproduce:
```commandline
$ forge init hello_foundry
$ cd hello_foundry
$ forge build --zksync
[⠃] Using zksolc-1.5.7
[⠢] Compiling (zksync)
[⠒] Compiling 27 files with zksolc and ZKsync solc 0.8.28
[⠢] zksolc and ZKsync solc 0.8.28 finished in 2.84s
Compiler run successful!
$ forge create --verbose --zksync  --rpc-url https://mainnet.era.zksync.io --private-key <private-key>  src/Counter.sol:Counter
[⠃] Using zksolc-1.5.7
[⠊] Compiling (zksync)
No files changed, compilation skipped
Deployer: 0x...
Deployed to: 0x...
$ forge create --verbose --zksync  --rpc-url https://rpc.zerion.io/v1/zero  --private-key <private-key> src/Counter.sol:Counter
[⠃] Using zksolc-1.5.7
[⠊] Compiling (zksync)
No files changed, compilation skipped
Error: contract was not deployed
```

**Comment by Jrigada** [comment]
Hello @jkylling,

This issue is related to the transaction receipt from the RPC node. The solution would be to update the RPC accordingly, which should resolve the problem. This is also why it works fine in zkSync.

You can find more details in this [thread](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/766#discussioncomment-11215020). I will keep the issue open to monitor if updating the RPC node resolves it.

**Comment by Jrigada** [comment]
I believe this issue has now been resolved, so I'll go ahead and close it. If the problem persists or you need further clarification, feel free to reopen it or create a new issue.
