### ISSUE TITLE
ssh vs git dependencies

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/foundry-zksync#79]
### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

For me to follow the `README.md` to the `cargo build -p foundry-cli` step, I had to setup SSH keys for github.

This will be a major hurdle for newer devs. 

Technically this isn't a "bug report" but it will be a major adoption hurdle, so a "Developer Experience Bug".

**Comment by berryhill** [comment]
@PatrickAlphaC thanks for picking up on this. Probably due to some of the zksync-era packages we're importing. Don't believe those are being published to crates.io yet but perhaps this is solvable prior to that.

https://github.com/matter-labs/foundry-zksync/blob/main/cli/Cargo.toml#L91

@sammyshakes @mm-zk might have more information regarding this.

**Comment by sammyshakes** [comment]
yea seeing this on a cargo test: 
```
Updating git repository `https://github.com/matter-labs/zksync-era.git`
    Updating git submodule `git@github.com:matter-labs/era-contracts.git`
error: failed to get `zksync` as a dependency of package `foundry-cli v0.2.0 (/home/runner/work/foundry-zksync/foundry-zksync/cli)`

Caused by:
  failed to load source for dependency `zksync`

Caused by:
  Unable to update https://github.com/matter-labs/zksync-era.git#48fe6e27

Caused by:
  failed to update submodule `contracts`

Caused by:
  failed to fetch submodule `contracts` from git@github.com:matter-labs/era-contracts.git

Caused by:
  failed to authenticate when downloading repository

  * attempted ssh-agent authentication, but no usernames succeeded: `git`
```

Which led me to the zksync-era repo [here](https://github.com/matter-labs/zksync-era/blob/48fe6e27110c1fe1a438c5375fb256890e8017b1/.gitmodules): 
```
[submodule "sdk/binaryen"]
	path = sdk/binaryen
	url = git@github.com:WebAssembly/binaryen.git
[submodule "etc/system-contracts"]
	path = etc/system-contracts
	url = git@github.com:matter-labs/era-system-contracts.git
[submodule "etc/openzeppelin-contracts"]
	path = etc/openzeppelin-contracts
	url = git@github.com:matter-labs/era-openzeppelin.git
[submodule "contracts"]
	path = contracts
	url = git@github.com:matter-labs/era-contracts.git
```

- I believe this should be an issue for the zksync-era repo. 
- some relevant info [here](https://stackoverflow.com/questions/6631694/replace-git-submodule-protocol-from-git-to-http)
- Another solution is we provide an executable, which i believe is coming soon, 
@mm-zk might have more information regarding this.

**Comment by mm-zk** [comment]
Yes, that's on us. Will fix it soon.

**Comment by mm-zk** [comment]
https://github.com/matter-labs/zksync-era/pull/37 should fix it (once it gets merged)

**Comment by mm-zk** [comment]
Fixed.
