### ISSUE TITLE
zkforge create: confusing error message when deploying a contract

### ISSUE THREAD

**Issue by tmrtx** [matter-labs/foundry-zksync#80]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What command(s) is the bug in?

zkforge create

### Operating System

Linux

### Describe the bug

After installing foundry-zksync and verifying that everything works with zkcast (balance, get-price, etc.). I've ran `zkforge init` and zkforge contract deploy cmd: 
`zkforge create src/Counter.sol:Counter --rpc-url https://zksync2-testnet.zksync.dev:443 --private-key "PK"`

The error I get is confusing, not sure where to go from here
```bash
[⠒] Compiling...
[⠆] Installing solc version 0.8.13
[⠑] Successfully installed solc 0.8.13
No files changed, compilation skipped
Error:
(code: -32601, message: Method not found, data: None)
```

**Comment by mm-zk** [comment]
uh.. nice catch @sammyshakes - is the "Method not found" coming from the zksync server?

**Comment by sammyshakes** [comment]
> uh.. nice catch @sammyshakes - is the "Method not found" coming from the zksync server?

yea coming from the forge create command trying to access zksync, its basically equivalent to an RPC error

**Comment by tmrtx** [comment]
@sammyshakes after using zk-create found another confusing error (submitted a PR https://github.com/matter-labs/foundry-zksync/pull/82). 

Turns out that I needed to run zkbuild before zk-create so that the `zkout` artifacts are created. If I just run `zk-create`, it errors out about not finding a file.
