### ISSUE TITLE
Deploy command fails when trying to deploy custom factory contract

### ISSUE THREAD

**Issue by 0xDEnYO** [matter-labs/foundry-zksync#85]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31fcf5a 2023-05-19T00:10:33.861185000Z)

### What command(s) is the bug in?

zkforge zk-create

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to deploy our custom version of a factory contract.
It imports from solmate which I have added as a submodule. The compiler runs fine, the artifact is produced and looks good.

However, when I try to deploy using this command, I get an error:
Command:
`../foundry-zksync/target/debug/zkforge zk-create src/is-system/CREATE3Factory.sol:CREATE3Factory --private-key ...`

Output:
```
Error:
Error getting bytecode from contract: invalid type: null, expected a string
```

Here the artifact:
<img width="1105" alt="image" src="https://github.com/matter-labs/foundry-zksync/assets/77058885/0c3d84bc-eebf-4656-924f-78fb40204c8c">

I believe the error happens in zkCreate.rs in function _get_bytecode_from_contract_

**Comment by sammyshakes** [comment]
i am having trouble reproducing this error. Can you provide a simplified example of your contract so i can try it, or possibly a repo with an example?

**Comment by 0xDEnYO** [comment]
This is the contract I am trying to deploy:

```
// SPDX-License-Identifier: AGPL-3.0
pragma solidity ^0.8.13;

import { CREATE3 } from "lib/solmate/src/utils/CREATE3.sol";

import { ICREATE3Factory } from "../ICREATE3Factory.sol";

/// @title Factory for deploying contracts to deterministic addresses via CREATE3
/// @author zefram.eth
/// @notice Enables deploying contracts using CREATE3. Each deployer (msg.sender) has
/// its own namespace for deployed addresses.
contract CREATE3Factory is ICREATE3Factory {
    /// @inheritdoc	ICREATE3Factory
    function deploy(
        bytes32 salt,
        bytes memory creationCode
    ) external payable override returns (address deployed) {
        // hash salt with the deployer address to give each deployer its own namespace
        salt = keccak256(abi.encodePacked(msg.sender, salt));
        return CREATE3.deploy(salt, creationCode, msg.value);
    }

    /// @inheritdoc	ICREATE3Factory
    function getDeployed(
        address deployer,
        bytes32 salt
    ) external view override returns (address deployed) {
        // hash salt with the deployer address to give each deployer its own namespace
        salt = keccak256(abi.encodePacked(deployer, salt));
        return CREATE3.getDeployed(salt);
    }
}
```

and here's the interface it imports:

```
// SPDX-License-Identifier: AGPL-3.0
pragma solidity >=0.6.0;

/// @title Factory for deploying contracts to deterministic addresses via CREATE3
/// @author zefram.eth
/// @notice Enables deploying contracts using CREATE3. Each deployer (msg.sender) has
/// its own namespace for deployed addresses.
interface ICREATE3Factory {
    /// @notice Deploys a contract using CREATE3
    /// @dev The provided salt is hashed together with msg.sender to generate the final salt
    /// @param salt The deployer-specific salt for determining the deployed contract's address
    /// @param creationCode The creation code of the contract to deploy
    /// @return deployed The address of the deployed contract
    function deploy(
        bytes32 salt,
        bytes memory creationCode
    ) external payable returns (address deployed);

    /// @notice Predicts the address of a deployed contract
    /// @dev The provided salt is hashed together with the deployer address to generate the final salt
    /// @param deployer The deployer account that will call deploy()
    /// @param salt The deployer-specific salt for determining the deployed contract's address
    /// @return deployed The address of the contract that will be deployed
    function getDeployed(
        address deployer,
        bytes32 salt
    ) external view returns (address deployed);
}

```

**Comment by mm-zk** [comment]
Hey @0xDEnYO - I've tried reproducing your issue - but I couldn't:
https://github.com/mm-zk/sample-fzksync-project/tree/0523_bug

I've run:
```
../../matter/foundry-zksync/target/debug/zkforge zk-build
```
and then:
```
../../matter/foundry-zksync/target/debug/zkforge zk-create src/is-system/CREATE3Factory.sol:CREATE3Factory --rpc-url http://localhost:3050 --chain 270 
```

to deploy on local network  - and it worked. 
Can you double-check that you've re-compiled your solidity (with zk-build)?

**Comment by mm-zk** [comment]
but I did find one scenario, when I get the same error -- when contract name differs.

```
../../matter/foundry-zksync/target/debug/zkforge zk-create src/is-system/CREATE3Factory.sol:WRONGNAMECREATE3Factory --rpc-url http://localhost:3050 --chain 270 

```

**Comment by 0xDEnYO** [comment]
> ild

Yeah I mean I did compile it, otherwise there wouldnt be an artifact, right?

When I try deploying locally I get the same error as when trying to deploy to testnet

<img width="926" alt="image" src="https://github.com/matter-labs/foundry-zksync/assets/77058885/95263a85-d980-48ab-aa7e-bbea77da06cd">

Contract name seems correct to me.
Maybe some settings somewhere? Maybe it's looking in the wrong directory for the artifact?

**Comment by mm-zk** [comment]
I've just merged: https://github.com/matter-labs/foundry-zksync/pull/86 - that should show better error messages.

**Comment by mm-zk** [comment]
found the problem:

Your file is called Create3Factory, and you call:
```
zk-create src/is-system/CREATE3Factory.sol:CREATE3Factory 
```
instead, you should call:
```
zk-create src/is-system/Create3Factory.sol:CREATE3Factory 
```

**Comment by mm-zk** [comment]
@sammyshakes - good point. we should probably change it, so that ETH_RPC_URL is always pointing at 'zksync era' - and we should introduce another variable (L1_URL ?) for the case of deposit/withdrawal.

**Comment by sammyshakes** [comment]
> 

yes can definitely do something like this

**Comment by sammyshakes** [comment]
> @sammyshakes - good point. we should probably change it, so that ETH_RPC_URL is always pointing at 'zksync era' - and we should introduce another variable (L1_URL ?) for the case of deposit/withdrawal.

yes can definitely do something like this

**Comment by mm-zk** [comment]
Done in #94
