### ISSUE TITLE
Running any of the compile commands crashes with a bug report

### ISSUE THREAD

**Issue by kailash-manasarovar** [matter-labs/foundry-zksync#89]
### Component

Other (please describe) -> not sure what to put here.

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am checking the README on this repo.

I am running into errors on the compile instructions, e.g.

```sh
sample-fzksync-project % ../foundry-zksync/target/debug/zkforge zk-build
Downloading zksolc compiler
Compiling smart contracts...
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Could not get solc: Unknown version provided
Location: cli/src/cmd/forge/zksolc.rs:564

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

This is a blocker because I cannot go forward to deploy or the other features while this is failing.

**Comment by sammyshakes** [comment]
Is this the sample project from the readme or are you trying to compile your own contracts? if your own, can you provide a simple example so I can try to reproduce the error?

**Comment by kailash-manasarovar** [comment]
> Is this the sample project from the readme or are you trying to compile your own contracts? if your own, can you provide a simple example so I can try to reproduce the error?

I'm following every step in the README to the letter.

**Comment by sammyshakes** [comment]
i believe this has to do with the chip architecture. We need to integrate ARM architecture

**Comment by mm-zk** [comment]
Found the issue - we didn't have proper support for Apple Silicon macs.

Fixed in: https://github.com/matter-labs/foundry-zksync/commit/9f225d22ab13e4ee707405c44655f8fd72239af3

Also added instructions to README - on what flags to add (`--use 0.8.17` for now).
