### ISSUE TITLE
[feature request] Forking ZkSync Era

### ISSUE THREAD

**Issue by nhynhyiddy** [matter-labs/foundry-zksync#99]
### Component

Forge

### Describe the feature you would like

To do test on forge with forking on the ZkSync chain just like other evm chains.

**Comment by mm-zk** [comment]
For now, we have a standalone tool for this - https://github.com/matter-labs/era-test-node 

And we're working on adding it into forge.

**Comment by uF4No** [comment]
@nhynhyiddy you can find more info about how to fork mainnet with the era-test-node in our docs: https://era.zksync.io/docs/tools/testing/era-test-node.html#forking-networks

**Comment by dutterbutter** [comment]
Forking cheatcodes are now supported.
